Repository smartdevicelink/sdl_ios, pull requests merged in 2018-04, with the labels that each got.

#920 fix: memory leaks in the SDLLifecycleManager
  SmartDeviceLink/SDLFileManager.m
  SmartDeviceLink/SDLLifecycleManager.m
  SmartDeviceLinkTests/DevAPISpecs/SDLFileManagerSpec.m
Labels: bug

#922 reset retry counter when accessory is connected
  SmartDeviceLink/SDLIAPTransport.m
Labels: bug

#924 Fix manager should not notify delegates of nil -> nil changes
  SmartDeviceLink/SDLLifecycleManager.m
Labels: bug, ready for review

#923 Added support for setting a custom CarWindow screen resolution
  SmartDeviceLink-iOS.podspec
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
  SmartDeviceLink-iOS.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  SmartDeviceLink.podspec
  SmartDeviceLink/SDLStreamingMediaLifecycleManager.m
  SmartDeviceLink/SmartDeviceLink.h
  SmartDeviceLinkTests/DevAPISpecs/SDLSoftButtonManagerSpec.m
  SmartDeviceLinkTests/SDLStreamingMediaLifecycleManagerSpec.m
Labels: bug, enhancement

#916 SDL 0088 System Capability Manager
  SmartDeviceLink-iOS.podspec
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
  SmartDeviceLink.podspec
  SmartDeviceLink/SDLLifecycleManager.h
  SmartDeviceLink/SDLLifecycleManager.m
  SmartDeviceLink/SDLManager.h
  SmartDeviceLink/SDLManager.m
  SmartDeviceLink/SDLSystemCapabilityManager.h
  SmartDeviceLink/SDLSystemCapabilityManager.m
  SmartDeviceLink/SmartDeviceLink.h
  SmartDeviceLinkTests/DevAPISpecs/SDLLifecycleManagerSpec.m
  SmartDeviceLinkTests/SDLScreenManagerSpec.m
  SmartDeviceLinkTests/SDLSystemCapabilityManagerSpec.m
  SmartDeviceLink_Example/Classes/ProxyManager.m
Labels: enhancement, proposal

#940 Hide lower layers: proxy, protocol, and transport
  SmartDeviceLink-iOS.podspec
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
  SmartDeviceLink-iOS.xcodeproj/xcshareddata/xcschemes/SmartDeviceLink.xcscheme
  SmartDeviceLink-iOS.xcodeproj/xcshareddata/xcschemes/SmartDeviceLinkSwift.xcscheme
  SmartDeviceLink.podspec
  SmartDeviceLink/SDLFocusableItemLocator.m
  SmartDeviceLink/SDLFocusableItemLocatorType.h
  SmartDeviceLink/SDLProxy.h
  SmartDeviceLink/SDLProxyFactory.h
  SmartDeviceLink/SDLRegisterAppInterface.h
  SmartDeviceLink/SDLRegisterAppInterface.m
  SmartDeviceLink/SDLStreamingMediaConfiguration.h
  SmartDeviceLink/SDLStreamingMediaConfiguration.m
  SmartDeviceLink/SDLStreamingMediaLifecycleManager.m
  SmartDeviceLink/SDLUploadFileOperation.m
  SmartDeviceLink/SmartDeviceLink.h
Labels: enhancement, proposal

#935 fix SDLTouchManager to handle all touch events in SDLOnTouchEvent
  SmartDeviceLink/SDLTouchManager.m
  SmartDeviceLinkTests/UtilitiesSpecs/Touches/SDLTouchManagerSpec.m
Labels: bug

#938 add nil check for lockViewController
  SmartDeviceLink/SDLLockScreenManager.m
  SmartDeviceLink/SDLLockScreenPresenter.m
Labels: bug
