Repository smartdevicelink/sdl_ios, pull requests merged in 2018-08, with the labels that each got.

#1011 Prevent thread deadlock when disconnecting the iPhone from the Head Unit
  SmartDeviceLink/SDLIAPSession.m
  SmartDeviceLink/SDLIAPTransport.m
Labels: bug

#1048 Fix/shutdown video session even in suspended state
  SmartDeviceLink/SDLStreamingVideoLifecycleManager.m
  SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m
Labels: bug

#991 SDL 0037 Expand Mobile Putfile RPC
  SmartDeviceLink-iOS.podspec
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
  SmartDeviceLink.podspec
  SmartDeviceLink/SDLConfiguration.h
  SmartDeviceLink/SDLConfiguration.m
  SmartDeviceLink/SDLFile.m
  SmartDeviceLink/SDLFileManager.h
  SmartDeviceLink/SDLFileManager.m
  SmartDeviceLink/SDLFileManagerConfiguration.h
  SmartDeviceLink/SDLFileManagerConfiguration.m
  SmartDeviceLink/SDLLifecycleManager.m
  SmartDeviceLink/SDLManager.m
  SmartDeviceLink/SDLNames.h
  SmartDeviceLink/SDLNames.m
  SmartDeviceLink/SDLPutFile.h
  SmartDeviceLink/SDLPutFile.m
  SmartDeviceLink/SDLPutFileResponse.h
  SmartDeviceLink/SDLResult.h
  SmartDeviceLink/SDLResult.m
  SmartDeviceLink/SDLTextAndGraphicManager.m
  SmartDeviceLink/SDLUploadFileOperation.m
  SmartDeviceLink/SmartDeviceLink.h
  SmartDeviceLinkTests/DevAPISpecs/SDLCheckChoiceVROptionalOperationSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLConfigurationSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLFileManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLLifecycleManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLMenuCellSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLMenuManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLPresentChoiceSetOperationSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLPresentKeyboardOperationSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLTextAndGraphicManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLUploadFileOperationSpec.m
  SmartDeviceLinkTests/RPCSpecs/EnumSpecs/SDLResultSpec.m
  SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLAddCommandSpec.m
  SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLAddSubMenuSpec.m
  SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLGetVehicleDataSpec.m
  SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLPutFileSpec.m
  SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLShowSpec.m
  SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLSubscribeVehicleDataSpec.m
  SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLUnsubscribeVehicleDataSpec.m
  SmartDeviceLinkTests/RPCSpecs/ResponseSpecs/SDLPutFileResponseSpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLClimateControlCapabilitiesSpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLClimateControlDataSpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLDisplayCapabilitiesSpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLImageSpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLRadioControlCapabilitiesSpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLRadioControlDataSpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLRemoteControlCapabilitiesSpec.m
  SmartDeviceLinkTests/SDLFileManagerConfigurationSpec.m
  SmartDeviceLink_Example/Classes/ProxyManager.m
  SmartDeviceLink_Example/ProxyManager.swift
Labels: enhancement, proposal

#1051 Fix presenting a keyboard shows the test cell
  SmartDeviceLink/SDLPresentKeyboardOperation.m
  SmartDeviceLinkTests/DevAPISpecs/SDLPresentKeyboardOperationSpec.m
Labels: bug

#1053 Updated SyncMsgVersion to v5.0.0
  SmartDeviceLink/SDLRegisterAppInterface.m
  SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLRegisterAppInterfaceSpec.m
Labels: enhancement

#1033 Implement SDL-0041 - App Icon Resumption
  SmartDeviceLink/SDLLifecycleManager.m
  SmartDeviceLink/SDLNames.h
  SmartDeviceLink/SDLNames.m
  SmartDeviceLink/SDLRegisterAppInterfaceResponse.h
  SmartDeviceLink/SDLRegisterAppInterfaceResponse.m
  SmartDeviceLinkTests/RPCSpecs/ResponseSpecs/SDLRegisterAppInterfaceResponseSpec.m
Labels: enhancement, proposal

#1049 Fix/shutdown video session in suspended state in sdl_ios v6.0.1
  SmartDeviceLink/SDLStreamingMediaLifecycleManager.m
  SmartDeviceLinkTests/SDLStreamingMediaLifecycleManagerSpec.m
Labels: bug

#1042 SDL 0064 Choice VR Optional
  SmartDeviceLink/SDLChoice.h
  SmartDeviceLink/SDLChoice.m
  SmartDeviceLink/SDLChoiceSet.m
  SmartDeviceLink/SDLMenuManager.m
  SmartDeviceLinkTests/DevAPISpecs/SDLChoiceSetSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLMenuManagerSpec.m
Labels: enhancement, proposal

#1046 Implement Revisions - SDL 0099 New remote control modules, SDL 0175 Updating DOP value range for GPS notification
  SmartDeviceLink-iOS.podspec
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
  SmartDeviceLink.podspec
  SmartDeviceLink/SDLEqualizerSettings.h
  SmartDeviceLink/SDLEqualizerSettings.m
  SmartDeviceLink/SDLGPSData.h
  SmartDeviceLink/SDLGPSData.m
  SmartDeviceLink/SDLGPSLocation.h
  SmartDeviceLink/SDLGPSLocation.m
  SmartDeviceLink/SDLLightCapabilities.h
  SmartDeviceLink/SDLLightCapabilities.m
  SmartDeviceLink/SDLLightControlData.h
  SmartDeviceLink/SDLLightControlData.m
  SmartDeviceLink/SDLLightName.h
  SmartDeviceLink/SDLLightName.m
  SmartDeviceLink/SDLLightState.h
  SmartDeviceLink/SDLLightState.m
  SmartDeviceLink/SDLNames.h
  SmartDeviceLink/SDLNames.m
  SmartDeviceLink/SDLRadioControlData.h
  SmartDeviceLink/SDLRadioControlData.m
  SmartDeviceLink/SDLSISData.h
  SmartDeviceLink/SDLSISData.m
  SmartDeviceLink/SDLSRGBColor.h
  SmartDeviceLink/SDLSRGBColor.m
  SmartDeviceLink/SmartDeviceLink.h
  SmartDeviceLinkTests/RPCSpecs/EnumSpecs/SDLLightNameSpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLEqualizerSettingsSpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLGPSLocationSpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLLightCapabilitiesSpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLLightControlDataSpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLLightStateSpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLRadioControlDataSpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLSDLSRGBColorSpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLSISDataSpec.m
Labels: proposal
