Repository smartdevicelink/sdl_ios, pull requests merged in 2018-11, with the labels that each got.

#1125 Remove duplicate logs
  SmartDeviceLink/SDLLifecycleManager.m
  SmartDeviceLink/SDLStreamingAudioLifecycleManager.m
  SmartDeviceLink/SDLStreamingVideoLifecycleManager.m
Labels: bug, documentation

#1116 DisplayLink issue when app gets (in)active on the phone
  SmartDeviceLink/SDLStreamingVideoLifecycleManager.m
Labels: bug

#1131 Fix: Reference cycle with video manager and display link causing touch issues
  SmartDeviceLink/SDLStreamingMediaManager.m
Labels: bug

#1134 Added verbose logging for recieved messages
  SmartDeviceLink/SDLProxy.m
Labels: enhancement

#1128 check class type to take care of language enum being “-1”
  SmartDeviceLink/SDLLifecycleManager.m
Labels: bug

#1123 Check class type to take care of the case textField.name has "long" type
  SmartDeviceLink/SDLDisplayCapabilities+ShowManagerExtensions.m
Labels: bug

#1114 fix to call sdl_retryEstablishSession after data sesion is closed
  SmartDeviceLink/SDLIAPTransport.m
Labels: bug

#1112 [SDL 0197] Implement updated SetMediaClockTimer initializers
  SmartDeviceLink/SDLSetMediaClockTimer.h
  SmartDeviceLink/SDLSetMediaClockTimer.m
  SmartDeviceLink/SDLStartTime.h
  SmartDeviceLink/SDLStartTime.m
  SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLSetMediaClockTimerSpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLStartTimeSpec.m
Labels: enhancement, proposal

#1106 [SDL-0196] Support Static Icon in Screen Manager
  Example Apps/Example ObjC/ButtonManager.m
  Example Apps/Example ObjC/PerformInteractionManager.m
  Example Apps/Example Swift/PerformInteractionManager.swift
  SmartDeviceLink/SDLArtwork.h
  SmartDeviceLink/SDLArtwork.m
  SmartDeviceLink/SDLChoiceSet.m
  SmartDeviceLink/SDLChoiceSetManager.m
  SmartDeviceLink/SDLError.h
  SmartDeviceLink/SDLError.m
  SmartDeviceLink/SDLErrorConstants.h
  SmartDeviceLink/SDLFile.h
  SmartDeviceLink/SDLFile.m
  SmartDeviceLink/SDLFileManager.m
  SmartDeviceLink/SDLMenuManager.m
  SmartDeviceLink/SDLPreloadChoicesOperation.m
  SmartDeviceLink/SDLSoftButtonManager.m
  SmartDeviceLink/SDLSoftButtonState.m
  SmartDeviceLink/SDLTextAndGraphicManager.m
  SmartDeviceLinkTests/DevAPISpecs/SDLArtworkSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLPreloadChoicesOperationSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLSoftButtonManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLTextAndGraphicManagerSpec.m
Labels: enhancement, proposal

#1107 SDL 0118 Video Streaming Backgrounded String
  SmartDeviceLink/CVPixelBufferRef+SDLUtil.m
  SmartDeviceLink/SDLLifecycleManager.m
  SmartDeviceLink/SDLStreamingMediaManager.h
  SmartDeviceLink/SDLStreamingMediaManager.m
  SmartDeviceLink/SDLStreamingVideoLifecycleManager.h
  SmartDeviceLink/SDLStreamingVideoLifecycleManager.m
  SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m
Labels: enhancement
