Repository smartdevicelink/sdl_ios, pull requests merged in 2018-05, with the labels that each got.

#930 Menu Manager
  SmartDeviceLink-iOS.podspec
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
  SmartDeviceLink.podspec
  SmartDeviceLink/SDLArtwork.m
  SmartDeviceLink/SDLAsynchronousRPCRequestOperation.h
  SmartDeviceLink/SDLAsynchronousRPCRequestOperation.m
  SmartDeviceLink/SDLConnectionManagerType.h
  SmartDeviceLink/SDLDisplayCapabilities+ShowManagerExtensions.m
  SmartDeviceLink/SDLError.h
  SmartDeviceLink/SDLError.m
  SmartDeviceLink/SDLErrorConstants.h
  SmartDeviceLink/SDLFile.m
  SmartDeviceLink/SDLLifecycleManager.m
  SmartDeviceLink/SDLLogFileModuleMap.m
  SmartDeviceLink/SDLManager.h
  SmartDeviceLink/SDLMenuCell.h
  SmartDeviceLink/SDLMenuCell.m
  SmartDeviceLink/SDLMenuManager.h
  SmartDeviceLink/SDLMenuManager.m
  SmartDeviceLink/SDLNotificationConstants.h
  SmartDeviceLink/SDLScreenManager.h
  SmartDeviceLink/SDLScreenManager.m
  SmartDeviceLink/SDLSoftButtonManager.m
  SmartDeviceLink/SDLVoiceCommand.h
  SmartDeviceLink/SDLVoiceCommand.m
  SmartDeviceLink/SDLVoiceCommandManager.h
  SmartDeviceLink/SDLVoiceCommandManager.m
  SmartDeviceLink/SmartDeviceLink.h
  SmartDeviceLinkTests/DevAPISpecs/SDLMenuCellSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLMenuManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLTextAndGraphicManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandSpec.m
  SmartDeviceLinkTests/TestUtilities/TestConnectionManager.m
  SmartDeviceLink_Example/Classes/ProxyManager.m
  SmartDeviceLink_Example/Images.xcassets/car.imageset/Contents.json
  SmartDeviceLink_Example/Images.xcassets/car.imageset/iconmonstr-car-1-64.png
  SmartDeviceLink_Example/Images.xcassets/choice_set.imageset/Contents.json
  SmartDeviceLink_Example/Images.xcassets/choice_set.imageset/iconmonstr-text-23-64.png
  SmartDeviceLink_Example/Images.xcassets/speak.imageset/Contents.json
  SmartDeviceLink_Example/Images.xcassets/speak.imageset/iconmonstr-speech-bubble-5-64.png
Labels: enhancement, proposal

#949 Refactor lower layers to remove uneeded cruft
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
  SmartDeviceLink/SDLAbstractProtocol.h
  SmartDeviceLink/SDLAbstractProtocol.m
  SmartDeviceLink/SDLAbstractTransport.m
  SmartDeviceLink/SDLIAPTransport.h
  SmartDeviceLink/SDLLifecycleManager.m
  SmartDeviceLink/SDLProtocol.h
  SmartDeviceLink/SDLProtocol.m
  SmartDeviceLink/SDLProtocolConstants.h
  SmartDeviceLink/SDLProtocolConstants.m
  SmartDeviceLink/SDLProtocolHeader.h
  SmartDeviceLink/SDLProxy.h
  SmartDeviceLink/SDLProxy.m
  SmartDeviceLink/SDLProxyFactory.h
  SmartDeviceLink/SDLProxyFactory.m
  SmartDeviceLink/SDLStreamingMediaLifecycleManager.h
  SmartDeviceLink/SDLStreamingMediaLifecycleManager.m
  SmartDeviceLink/SDLStreamingMediaManager.h
  SmartDeviceLink/SDLStreamingMediaManager.m
  SmartDeviceLink/SDLTCPTransport.h
  SmartDeviceLink/SDLTCPTransport.m
  SmartDeviceLink/SDLTransportType.h
  SmartDeviceLinkTests/DevAPISpecs/SDLLifecycleManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLMenuManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLResponseDispatcherSpec.m
  SmartDeviceLinkTests/ProtocolSpecs/MessageSpecs/SDLProtocolSpec.m
  SmartDeviceLinkTests/ProtocolSpecs/SDLAbstractProtocolSpec.m
  SmartDeviceLinkTests/SDLStreamingMediaLifecycleManagerSpec.m
Labels: best practice

#951 Fixed incorrect VR capability in the system capability manager
  SmartDeviceLink/SDLSystemCapabilityManager.m
Labels: bug

#958 Fixed image soft buttons getting sent early
  SmartDeviceLink/SDLSoftButtonManager.m
  SmartDeviceLinkTests/DevAPISpecs/SDLSoftButtonManagerSpec.m
Labels: bug

#956 Reset screen manager after disconnects
  SmartDeviceLink/SDLLifecycleManager.m
  SmartDeviceLink/SDLMenuManager.h
  SmartDeviceLink/SDLMenuManager.m
  SmartDeviceLink/SDLScreenManager.h
  SmartDeviceLink/SDLScreenManager.m
  SmartDeviceLink/SDLSoftButtonManager.h
  SmartDeviceLink/SDLSoftButtonManager.m
  SmartDeviceLink/SDLTextAndGraphicManager.h
  SmartDeviceLink/SDLTextAndGraphicManager.m
  SmartDeviceLink/SDLVoiceCommandManager.h
  SmartDeviceLink/SDLVoiceCommandManager.m
Labels: bug

#962 Fix custom log modules in Swift
  SmartDeviceLinkSwift/SDLLog.swift
Labels: bug

#964 Fix permission manager reset when the connection closes
  SmartDeviceLink/SDLPermissionManager.m
  SmartDeviceLinkTests/DevAPISpecs/SDLPermissionsManagerSpec.m
Labels: bug

#969 Fix media track field in ScreenManager
  SmartDeviceLink/SDLTextAndGraphicManager.m
  SmartDeviceLinkTests/DevAPISpecs/SDLTextAndGraphicManagerSpec.m
Labels: bug

#978 Stops reconnect on AppUnauthorized notifications
  SmartDeviceLink/SDLLifecycleManager.m
Labels: bug

#985 Truncated the generated `SDLArtwork` filename to 16 characters
  SmartDeviceLink/SDLArtwork.m
  SmartDeviceLinkTests/DevAPISpecs/SDLArtworkSpec.m
Labels: bug
