Repository smartdevicelink/sdl_ios, pull requests merged in 2018-02, with the labels that each got.

#855 Add `additionalHMITypes` to SDLLifecycleConfiguration
  SmartDeviceLink/SDLConfiguration.m
  SmartDeviceLink/SDLLifecycleConfiguration.h
  SmartDeviceLink/SDLLifecycleConfiguration.m
  SmartDeviceLink/SDLLifecycleManager.m
  SmartDeviceLink/SDLRegisterAppInterface.h
  SmartDeviceLink/SDLRegisterAppInterface.m
  SmartDeviceLinkTests/DevAPISpecs/SDLLifecycleConfigurationSpec.m
Labels: enhancement, proposal

#866 Check if output stream has space before sending data
  SmartDeviceLink/SDLIAPSession.m
Labels: bug

#870 Close EA session before reconnect
  SmartDeviceLink/SDLProxy.m
Labels: bug, ready for review

#836 Start background task when data is received from ea session
  SmartDeviceLink/SDLIAPTransport.m
Labels: bug, ready for review

#871 fix to stop audio streaming at HMI level none and background (resubmission of #804)
  SmartDeviceLink/SDLStreamingMediaLifecycleManager.m
  SmartDeviceLinkTests/SDLStreamingMediaLifecycleManagerSpec.m
Labels: bug, ready for review

#729 Implement SDL 0054 ChangeRegistration-Manager
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
  SmartDeviceLink/SDLLifecycleConfiguration.h
  SmartDeviceLink/SDLLifecycleConfigurationUpdate.h
  SmartDeviceLink/SDLLifecycleConfigurationUpdate.m
  SmartDeviceLink/SDLLifecycleManager.h
  SmartDeviceLink/SDLLifecycleManager.m
  SmartDeviceLink/SDLManagerDelegate.h
  SmartDeviceLink/SmartDeviceLink.h
  SmartDeviceLinkTests/DevAPISpecs/SDLLifecycleConfigurationSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLLifecycleManagerSpec.m
Labels: enhancement, proposal

#873 Fix SDLLogTargetFile bug
  SmartDeviceLink/SDLLogTargetFile.m
Labels: bug, ready for review

#857 Batch sending of RPC Requests
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
  SmartDeviceLink/SDLAsynchronousRPCRequestOperation.h
  SmartDeviceLink/SDLAsynchronousRPCRequestOperation.m
  SmartDeviceLink/SDLConnectionManagerType.h
  SmartDeviceLink/SDLDeleteFileOperation.m
  SmartDeviceLink/SDLError.h
  SmartDeviceLink/SDLError.m
  SmartDeviceLink/SDLErrorConstants.h
  SmartDeviceLink/SDLFocusableItemLocator.m
  SmartDeviceLink/SDLLifecycleManager.h
  SmartDeviceLink/SDLLifecycleManager.m
  SmartDeviceLink/SDLListFilesOperation.m
  SmartDeviceLink/SDLManager.h
  SmartDeviceLink/SDLManager.m
  SmartDeviceLink/SDLSequentialRPCRequestOperation.h
  SmartDeviceLink/SDLSequentialRPCRequestOperation.m
  SmartDeviceLink/SDLStreamingMediaLifecycleManager.m
  SmartDeviceLink/SDLUploadFileOperation.m
  SmartDeviceLinkTests/DevAPISpecs/SDLAsynchronousRPCRequestOperationSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLFileManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLLifecycleManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLSequentialRPCRequestOperationSpec.m
  SmartDeviceLinkTests/ProxySpecs/SDLHapticManagerSpec.m
  SmartDeviceLinkTests/TestFileProgressResponse.h
  SmartDeviceLinkTests/TestFileProgressResponse.m
  SmartDeviceLinkTests/TestMultipleFilesConnectionManager.m
  SmartDeviceLinkTests/TestUtilities/SDLSpecUtilities.h
  SmartDeviceLinkTests/TestUtilities/SDLSpecUtilities.m
  SmartDeviceLinkTests/TestUtilities/TestConnectionManager.m
  SmartDeviceLinkTests/TestUtilities/TestMultipleRequestsConnectionManager.h
  SmartDeviceLinkTests/TestUtilities/TestMultipleRequestsConnectionManager.m
  SmartDeviceLinkTests/TestUtilities/TestRequestProgressResponse.h
  SmartDeviceLinkTests/TestUtilities/TestRequestProgressResponse.m
  SmartDeviceLink_Example/Classes/ProxyManager.m
Labels: enhancement, proposal, ready for review
