Repository smartdevicelink/sdl_ios, pull requests merged in 2018-03, with the labels that each got.

#883 Fixed main thread warnings in the `SDLTouchManager` class
  SmartDeviceLink/SDLTouchManager.m
Labels: best practice

#878 Video stream is stopped as soon as app enters background
  SmartDeviceLink/SDLStreamingMediaLifecycleManager.m
Labels: bug

#874 SDL 0124 Image Upload Manager
  SmartDeviceLink/SDLArtwork.h
  SmartDeviceLink/SDLArtwork.m
  SmartDeviceLink/SDLError.h
  SmartDeviceLink/SDLError.m
  SmartDeviceLink/SDLErrorConstants.h
  SmartDeviceLink/SDLFileManager.h
  SmartDeviceLink/SDLFileManager.m
  SmartDeviceLink/SDLFileManagerConstants.h
  SmartDeviceLink/SDLImage.h
  SmartDeviceLink/SDLImage.m
  SmartDeviceLinkTests/DevAPISpecs/SDLArtworkSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLFileManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLLifecycleConfigurationSpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLImageSpec.m
  SmartDeviceLinkTests/TestMultipleFilesConnectionManager.m
  SmartDeviceLink_Example/Classes/ProxyManager.m
Labels: enhancement, proposal

#890 Fixed incorrect target membership for class (CocoaPods)
  SmartDeviceLink-iOS.podspec
  SmartDeviceLink.podspec
Labels: bug, ready for review

#884 Pan gesture blocks single taps
  SmartDeviceLink/SDLTouchManager.h
  SmartDeviceLink/SDLTouchManager.m
  SmartDeviceLinkTests/UtilitiesSpecs/Touches/SDLTouchManagerSpec.m
Labels: bug

#885 Fix the broken test cases
  SmartDeviceLink/SDLTouchManager.m
  SmartDeviceLinkTests/DevAPISpecs/SDLLifecycleManagerSpec.m
  SmartDeviceLinkTests/SDLStreamingMediaLifecycleManagerSpec.m
Labels: bug, testing

#889 Show / Screen Manager
  SmartDeviceLink-iOS.podspec
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
  SmartDeviceLink.podspec
  SmartDeviceLink/SDLArtwork.h
  SmartDeviceLink/SDLConnectionManagerType.h
  SmartDeviceLink/SDLDisplayCapabilities+ShowManagerExtensions.h
  SmartDeviceLink/SDLDisplayCapabilities+ShowManagerExtensions.m
  SmartDeviceLink/SDLError.h
  SmartDeviceLink/SDLError.m
  SmartDeviceLink/SDLErrorConstants.h
  SmartDeviceLink/SDLFileManager.h
  SmartDeviceLink/SDLFileManager.m
  SmartDeviceLink/SDLLifecycleManager.h
  SmartDeviceLink/SDLLifecycleManager.m
  SmartDeviceLink/SDLLogFileModuleMap.m
  SmartDeviceLink/SDLManager.h
  SmartDeviceLink/SDLManager.m
  SmartDeviceLink/SDLProxy.m
  SmartDeviceLink/SDLScreenManager.h
  SmartDeviceLink/SDLScreenManager.m
  SmartDeviceLink/SDLSoftButtonManager.h
  SmartDeviceLink/SDLSoftButtonManager.m
  SmartDeviceLink/SDLSoftButtonObject.h
  SmartDeviceLink/SDLSoftButtonObject.m
  SmartDeviceLink/SDLSoftButtonState.h
  SmartDeviceLink/SDLSoftButtonState.m
  SmartDeviceLink/SDLTextAndGraphicManager.h
  SmartDeviceLink/SDLTextAndGraphicManager.m
  SmartDeviceLink/SmartDeviceLink.h
  SmartDeviceLinkTests/DevAPISpecs/SDLLifecycleManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLSoftButtonManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLSoftButtonStateSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLTextAndGraphicManagerSpec.m
  SmartDeviceLinkTests/SDLScreenManagerSpec.m
  SmartDeviceLinkTests/SDLSoftButtonObjectSpec.m
  SmartDeviceLink_Example/Classes/ProxyManager.m
  SmartDeviceLink_Example/Images.xcassets/AppIcon.appiconset/Contents.json
Labels: enhancement, proposal, ready for review

#903 Fixed change registration not sent
  SmartDeviceLink/SDLLifecycleManager.m
Labels: bug

#905 Fix a crash on iOS 9 when video streaming is started
  SmartDeviceLink/SDLStreamingMediaLifecycleManager.m
Labels: bug
