Repository smartdevicelink/sdl_ios, pull requests merged in 2019-08, with the labels that each got.

#1296 Implement SDL-0119 - SDL Passenger Mode
  SmartDeviceLink/SDLLockScreenManager.h
  SmartDeviceLink/SDLLockScreenManager.m
  SmartDeviceLink/SDLLockScreenStatus.h
  SmartDeviceLink/SDLLockScreenStatusManager.h
  SmartDeviceLink/SDLLockScreenStatusManager.m
  SmartDeviceLink/SDLLockScreenViewController.h
  SmartDeviceLink/SDLLockScreenViewController.m
  SmartDeviceLink/SDLOnDriverDistraction.h
  SmartDeviceLink/SDLOnDriverDistraction.m
  SmartDeviceLink/SDLOnLockScreenStatus.h
  SmartDeviceLink/SDLOnLockScreenStatus.m
  SmartDeviceLink/SDLProxyListener.h
  SmartDeviceLink/SDLRPCParameterNames.h
  SmartDeviceLink/SDLRPCParameterNames.m
  SmartDeviceLinkTests/DevAPISpecs/SDLLockScreenManagerSpec.m
  SmartDeviceLinkTests/ProxySpecs/SDLLockScreenStatusManagerSpec.m
  SmartDeviceLinkTests/RPCSpecs/NotificationSpecs/SDLOnDriverDistractionSpec.m
  SmartDeviceLinkTests/RPCSpecs/NotificationSpecs/SDLOnLockScreenStatusSpec.m
Labels: enhancement, proposal

#1351 Implement SDL-0116 Open Menu RPC
  SmartDeviceLink-iOS.podspec
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
  SmartDeviceLink.podspec
  SmartDeviceLink/SDLFunctionID.m
  SmartDeviceLink/SDLMenuManager.h
  SmartDeviceLink/SDLMenuManager.m
  SmartDeviceLink/SDLNotificationConstants.h
  SmartDeviceLink/SDLNotificationConstants.m
  SmartDeviceLink/SDLNotificationDispatcher.m
  SmartDeviceLink/SDLProxyListener.h
  SmartDeviceLink/SDLRPCFunctionNames.h
  SmartDeviceLink/SDLRPCFunctionNames.m
  SmartDeviceLink/SDLScreenManager.h
  SmartDeviceLink/SDLScreenManager.m
  SmartDeviceLink/SDLShowAppMenu.h
  SmartDeviceLink/SDLShowAppMenu.m
  SmartDeviceLink/SDLShowAppMenuResponse.h
  SmartDeviceLink/SDLShowAppMenuResponse.m
  SmartDeviceLink/SmartDeviceLink.h
  SmartDeviceLinkTests/DevAPISpecs/SDLMenuManagerSpec.m
  SmartDeviceLinkTests/Notifications/SDLNotificationDispatcherSpec.m
  SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLShowAppMenuSpec.m
  SmartDeviceLinkTests/RPCSpecs/ResponseSpecs/SDLShowAppMenuResponseSpec.m
  SmartDeviceLinkTests/SDLScreenManagerSpec.m
Labels: enhancement, proposal

#1366 Add config option to disable lock screen dismiss gesture
  SmartDeviceLink/SDLLockScreenConfiguration.h
  SmartDeviceLink/SDLLockScreenConfiguration.m
  SmartDeviceLink/SDLLockScreenManager.m
  SmartDeviceLinkTests/DevAPISpecs/SDLLockScreenConfigurationSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLLockScreenManagerSpec.m
Labels: enhancement

#1357 Implement SDL-0237 Add Feature to Disable "Video Streaming Backgrounded String" Feature
  SmartDeviceLink/SDLStreamingMediaManager.h
  SmartDeviceLink/SDLStreamingMediaManager.m
  SmartDeviceLink/SDLStreamingVideoLifecycleManager.h
  SmartDeviceLink/SDLStreamingVideoLifecycleManager.m
  SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m
Labels: enhancement, proposal

#1369 Fix TemplatesAvailable Documentation
  SmartDeviceLink/SDLDisplayCapabilities.h
Labels: documentation

#1384 Add Slider and Scrollable Message example apps
  Example Apps/Example ObjC/MenuManager.m
  Example Apps/Example Swift/MenuManager.swift
  Example Apps/Shared/AppConstants.h
  Example Apps/Shared/AppConstants.m
Labels: example app

#1371 Add option to hide device logo in SDLLockScreenViewController
  SmartDeviceLink/SDLLockScreenConfiguration.h
  SmartDeviceLink/SDLLockScreenConfiguration.m
  SmartDeviceLink/SDLLockScreenManager.m
  SmartDeviceLinkTests/DevAPISpecs/SDLLockScreenConfigurationSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLLockScreenManagerSpec.m
Labels: enhancement

#1376 Add a single state soft button object without having to create a stat…
  SmartDeviceLink/SDLSoftButtonObject.h
  SmartDeviceLink/SDLSoftButtonObject.m
  SmartDeviceLinkTests/SDLSoftButtonObjectSpec.m
Labels: enhancement

#1381 Configuration Option for Secondary Transports
  SmartDeviceLink/SDLLifecycleConfiguration.h
  SmartDeviceLink/SDLLifecycleConfiguration.m
  SmartDeviceLink/SDLLifecycleManager.m
  SmartDeviceLinkTests/DevAPISpecs/SDLLifecycleManagerSpec.m
Labels: enhancement

#1378 Add a setting to have the lock screen always display while connected
  SmartDeviceLink/SDLLockScreenConfiguration.h
  SmartDeviceLink/SDLLockScreenConfiguration.m
  SmartDeviceLink/SDLLockScreenManager.m
  SmartDeviceLinkTests/DevAPISpecs/SDLFakeViewControllerPresenter.m
  SmartDeviceLinkTests/DevAPISpecs/SDLLockScreenManagerSpec.m
Labels: enhancement
