Repository smartdevicelink/sdl_ios, pull requests merged in 2019-07, with the labels that each got.

#1324 Updated RegisterAppInterface class header file documentation
  SmartDeviceLink/SDLRegisterAppInterface.h
  SmartDeviceLink/SDLRegisterAppInterfaceResponse.h
Labels: enhancement

#1330 do not unregister EA accessory notification on transport dealloc
  SmartDeviceLink/SDLIAPTransport.m
Labels: bug

#1337 New RPC CloseApplication
  SmartDeviceLink-iOS.podspec
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
  SmartDeviceLink.podspec
  SmartDeviceLink/SDLCloseApplication.h
  SmartDeviceLink/SDLCloseApplication.m
  SmartDeviceLink/SDLCloseApplicationResponse.h
  SmartDeviceLink/SDLCloseApplicationResponse.m
  SmartDeviceLink/SDLFunctionID.m
  SmartDeviceLink/SDLNotificationConstants.h
  SmartDeviceLink/SDLNotificationConstants.m
  SmartDeviceLink/SDLNotificationDispatcher.m
  SmartDeviceLink/SDLProxyListener.h
  SmartDeviceLink/SDLRPCFunctionNames.h
  SmartDeviceLink/SDLRPCFunctionNames.m
  SmartDeviceLink/SmartDeviceLink.h
  SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLCloseApplicationSpec.m
  SmartDeviceLinkTests/RPCSpecs/ResponseSpecs/SDLCloseApplicationResponseSpec.m
Labels: enhancement, proposal

#1299 Implement SDL 0199 Adding-GPS-Shift-support
  SmartDeviceLink/SDLGPSData.h
  SmartDeviceLink/SDLGPSData.m
  SmartDeviceLink/SDLRPCParameterNames.h
  SmartDeviceLink/SDLRPCParameterNames.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLGPSDataSpec.m
Labels: enhancement, proposal

#1345 Update MaxProxyRPCVersion to 6.0.0
  SmartDeviceLink/SDLGlobals.m
  SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLRegisterAppInterfaceSpec.m
Labels: enhancement

#1333 Background task for establishing transport session now stopped when lifecycle manager reaches ready state
  SmartDeviceLink/SDLLifecycleManager.m
Labels: bug

#1336 Hotfix Release 6.3.1
  SmartDeviceLink/SDLIAPTransport.m
Labels: release

#1348 Implement SDL-0187 Restructure iOS Threading and Queueing
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
  SmartDeviceLink-iOS.xcodeproj/xcshareddata/xcschemes/SmartDeviceLink.xcscheme
  SmartDeviceLink/CVPixelBufferRef+SDLUtil.m
  SmartDeviceLink/SDLAsynchronousOperation.m
  SmartDeviceLink/SDLAsynchronousRPCRequestOperation.m
  SmartDeviceLink/SDLAudioStreamManager.m
  SmartDeviceLink/SDLCheckChoiceVROptionalOperation.m
  SmartDeviceLink/SDLChoiceSetManager.m
  SmartDeviceLink/SDLDeleteChoicesOperation.m
  SmartDeviceLink/SDLDeleteFileOperation.h
  SmartDeviceLink/SDLDeleteFileOperation.m
  SmartDeviceLink/SDLFile.m
  SmartDeviceLink/SDLFileManager.m
  SmartDeviceLink/SDLFocusableItemLocator.m
  SmartDeviceLink/SDLGlobals.h
  SmartDeviceLink/SDLGlobals.m
  SmartDeviceLink/SDLLifecycleManager.m
  SmartDeviceLink/SDLListFilesOperation.h
  SmartDeviceLink/SDLListFilesOperation.m
  SmartDeviceLink/SDLLogFileModuleMap.m
  SmartDeviceLink/SDLLogManager.m
  SmartDeviceLink/SDLMenuManager.m
  SmartDeviceLink/SDLPreloadChoicesOperation.m
  SmartDeviceLink/SDLPresentChoiceSetOperation.m
  SmartDeviceLink/SDLPresentKeyboardOperation.m
  SmartDeviceLink/SDLProtocol.m
  SmartDeviceLink/SDLProxy.m
  SmartDeviceLink/SDLRPCRequest.m
  SmartDeviceLink/SDLRPCResponse.m
  SmartDeviceLink/SDLResponseDispatcher.m
  SmartDeviceLink/SDLTouch.m
  SmartDeviceLink/SDLTouchManager.m
  SmartDeviceLink/SDLUploadFileOperation.h
  SmartDeviceLink/SDLUploadFileOperation.m
  SmartDeviceLink/dispatch_timer.h
  SmartDeviceLink/dispatch_timer.m
  SmartDeviceLinkTests/DevAPISpecs/SDLAsynchronousRPCRequestOperationSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLFileManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLLifecycleManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLMenuManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLUploadFileOperationSpec.m
  SmartDeviceLinkTests/ProxySpecs/SDLHapticManagerSpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLSystemCapabilitySpec.m
  SmartDeviceLinkTests/ReferenceImages_64/SDLLockScreenViewControllerSnapshotTests/testAppAndVehicleIcons@2x.png
  SmartDeviceLinkTests/ReferenceImages_64/SDLLockScreenViewControllerSnapshotTests/testAppAndVehicleIcons@3x.png
  SmartDeviceLinkTests/ReferenceImages_64/SDLLockScreenViewControllerSnapshotTests/testLightBackgroundNoAppNoVehicleIcons@2x.png
  SmartDeviceLinkTests/ReferenceImages_64/SDLLockScreenViewControllerSnapshotTests/testLightBackgroundNoAppNoVehicleIcons@3x.png
  SmartDeviceLinkTests/ReferenceImages_64/SDLLockScreenViewControllerSnapshotTests/testNoAppNoVehicleIcons@2x.png
  SmartDeviceLinkTests/ReferenceImages_64/SDLLockScreenViewControllerSnapshotTests/testNoAppNoVehicleIcons@3x.png
  SmartDeviceLinkTests/ReferenceImages_64/SDLLockScreenViewControllerSnapshotTests/testOnlyAppIcon@2x.png
  SmartDeviceLinkTests/ReferenceImages_64/SDLLockScreenViewControllerSnapshotTests/testOnlyAppIcon@3x.png
  SmartDeviceLinkTests/ReferenceImages_64/SDLLockScreenViewControllerSnapshotTests/testOnlyVehicleIcon@2x.png
  SmartDeviceLinkTests/ReferenceImages_64/SDLLockScreenViewControllerSnapshotTests/testOnlyVehicleIcon@3x.png
  SmartDeviceLinkTests/SDLAsynchronousRPCOperationSpec.m
  SmartDeviceLinkTests/TestResponse.m
  SmartDeviceLinkTests/TestUtilities/TestRequestProgressResponse.m
  SmartDeviceLinkTests/UtilitiesSpecs/Touches/DispatchTimerSpec.m
  SmartDeviceLinkTests/UtilitiesSpecs/Touches/SDLTouchManagerSpec.m
Labels: enhancement, proposal

#1342 Implement SDL-0224 Navigation Subscription Buttons
  SmartDeviceLink/SDLButtonName.h
  SmartDeviceLink/SDLButtonName.m
Labels: enhancement, proposal

#1349 Implement SDL-0225 Update Published App Services
  SmartDeviceLink-iOS.podspec
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
  SmartDeviceLink.podspec
  SmartDeviceLink/SDLFunctionID.m
  SmartDeviceLink/SDLNotificationConstants.h
  SmartDeviceLink/SDLNotificationConstants.m
  SmartDeviceLink/SDLNotificationDispatcher.m
  SmartDeviceLink/SDLProxyListener.h
  SmartDeviceLink/SDLPublishAppService.h
  SmartDeviceLink/SDLRPCFunctionNames.h
  SmartDeviceLink/SDLRPCFunctionNames.m
  SmartDeviceLink/SDLUnpublishAppService.h
  SmartDeviceLink/SDLUnpublishAppService.m
  SmartDeviceLink/SDLUnpublishAppServiceResponse.h
  SmartDeviceLink/SDLUnpublishAppServiceResponse.m
  SmartDeviceLink/SmartDeviceLink.h
  SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLUnpublishAppServiceSpec.m
  SmartDeviceLinkTests/RPCSpecs/ResponseSpecs/SDLUnpublishAppServiceResponseSpec.m
  SmartDeviceLinkTests/SDLRPCFunctionNamesSpec.m
Labels: enhancement, proposal

#1328 Implement SDL-0223 Add Currently Playing Media Image to MediaServiceData
  SmartDeviceLink/SDLMediaServiceData.h
  SmartDeviceLink/SDLMediaServiceData.m
  SmartDeviceLink/SDLRPCParameterNames.h
  SmartDeviceLink/SDLRPCParameterNames.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLMediaServiceDataSpec.m
Labels: enhancement

#1019 Implement SDL-0108 - AutoComplete List
  Example Apps/Example ObjC/PerformInteractionManager.m
  Example Apps/Example Swift/PerformInteractionManager.swift
  SmartDeviceLink/SDLKeyboardDelegate.h
  SmartDeviceLink/SDLKeyboardProperties.h
  SmartDeviceLink/SDLKeyboardProperties.m
  SmartDeviceLink/SDLPresentChoiceSetOperation.m
  SmartDeviceLink/SDLPresentKeyboardOperation.m
  SmartDeviceLink/SDLRPCParameterNames.h
  SmartDeviceLink/SDLRPCParameterNames.m
  SmartDeviceLinkTests/DevAPISpecs/SDLPresentChoiceSetOperationSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLPresentKeyboardOperationSpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLKeyboardPropertiesSpec.m
Labels: enhancement, proposal

#1362 Fix VR-only PICS failing in example apps
  Example Apps/Example ObjC/PerformInteractionManager.m
  Example Apps/Example Swift/PerformInteractionManager.swift
  Example Apps/Shared/AppConstants.h
  Example Apps/Shared/AppConstants.m
Labels: bug

#1359 Fix the Permission Manager sending too many observer updates
  SmartDeviceLink/SDLPermissionManager.m
  SmartDeviceLinkTests/DevAPISpecs/SDLPermissionsManagerSpec.m
Labels: bug

#1340 Implement SDL-0186 Template Titles
  Example Apps/Example ObjC/ProxyManager.m
  Example Apps/Example Swift/ProxyManager.swift
  SmartDeviceLink/SDLRPCParameterNames.h
  SmartDeviceLink/SDLRPCParameterNames.m
  SmartDeviceLink/SDLScreenManager.h
  SmartDeviceLink/SDLScreenManager.m
  SmartDeviceLink/SDLShow.h
  SmartDeviceLink/SDLShow.m
  SmartDeviceLink/SDLTextAndGraphicManager.h
  SmartDeviceLink/SDLTextAndGraphicManager.m
  SmartDeviceLink/SDLTextFieldName.h
  SmartDeviceLink/SDLTextFieldName.m
  SmartDeviceLinkTests/DevAPISpecs/SDLTextAndGraphicManagerSpec.m
  SmartDeviceLinkTests/RPCSpecs/EnumSpecs/SDLTextFieldNameSpec.m
  SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLShowSpec.m
Labels: enhancement, proposal

#1341 Implement SDL-0177 Alert Icon
  Example Apps/Example ObjC/AlertManager.h
  Example Apps/Example ObjC/AlertManager.m
  Example Apps/Example ObjC/AudioManager.m
  Example Apps/Example ObjC/ButtonManager.m
  Example Apps/Example ObjC/MenuManager.m
  Example Apps/Example ObjC/VehicleDataManager.m
  Example Apps/Example Swift/AlertManager.swift
  Example Apps/Example Swift/ButtonManager.swift
  SmartDeviceLink/SDLAlert.h
  SmartDeviceLink/SDLAlert.m
  SmartDeviceLink/SDLImageFieldName.h
  SmartDeviceLink/SDLImageFieldName.m
  SmartDeviceLink/SDLRPCParameterNames.h
  SmartDeviceLink/SDLRPCParameterNames.m
  SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLAlertSpec.m
Labels: enhancement, proposal
