Repository smartdevicelink/sdl_ios, pull requests merged in 2019-03, with the labels that each got.

#1164 Implement SDL-0208 - Block SDL Head Units
  SmartDeviceLink-iOS.podspec
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
  SmartDeviceLink.podspec
  SmartDeviceLink/SDLGlobals.h
  SmartDeviceLink/SDLGlobals.m
  SmartDeviceLink/SDLLifecycleConfiguration.h
  SmartDeviceLink/SDLLifecycleConfiguration.m
  SmartDeviceLink/SDLLifecycleManager.m
  SmartDeviceLink/SDLLogFileModuleMap.m
  SmartDeviceLink/SDLProtocol.m
  SmartDeviceLink/SDLProxy.m
  SmartDeviceLink/SDLStateMachine.m
  SmartDeviceLink/SDLVersion.h
  SmartDeviceLink/SDLVersion.m
  SmartDeviceLink/SmartDeviceLink.h
  SmartDeviceLinkTests/DevAPISpecs/SDLLifecycleConfigurationSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLLifecycleManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLStateMachineSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLUploadFileOperationSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLVersionSpec.m
  SmartDeviceLinkTests/ProtocolSpecs/MessageSpecs/SDLProtocolSpec.m
  SmartDeviceLinkTests/ProtocolSpecs/SDLProtocolMessageDisassemblerSpec.m
  SmartDeviceLinkTests/UtilitiesSpecs/SDLGlobalsSpec.m
Labels: enhancement

#1135 Add an explicit crash if an invalid soft button state is created
  SmartDeviceLink/SDLSoftButtonState.m
  SmartDeviceLinkTests/DevAPISpecs/SDLSoftButtonStateSpec.m
Labels: best practice

#1189 Added a convenience init to `GetAppServiceData` struct
  SmartDeviceLink/SDLGetAppServiceData.h
  SmartDeviceLink/SDLGetAppServiceData.m
  SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLGetAppServiceDataSpec.m
Labels: best practice

#1192 Made service data param nullable
  SmartDeviceLink/SDLGetAppServiceDataResponse.h
  SmartDeviceLink/SDLGetAppServiceDataResponse.m
Labels: bug

#1187 Fixed the documentation to match the RPC Spec for App Services
  SmartDeviceLink/SDLAppServiceData.h
  SmartDeviceLink/SDLGetAppServiceDataResponse.h
  SmartDeviceLink/SDLGetFile.h
  SmartDeviceLink/SDLGetFileResponse.h
  SmartDeviceLink/SDLNavigationInstruction.h
  SmartDeviceLink/SDLPerformAppServiceInteraction.h
  SmartDeviceLink/SDLPerformAppServiceInteractionResponse.h
Labels: documentation

#1195 Update param name in `SDLWeatherData` struct
  SmartDeviceLink/SDLRPCParameterNames.h
  SmartDeviceLink/SDLRPCParameterNames.m
  SmartDeviceLink/SDLWeatherData.h
  SmartDeviceLink/SDLWeatherData.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLWeatherDataSpec.m
Labels: bug

#1196 Update sendlocation documentation and add a corresponding initializer
  SmartDeviceLink/SDLSendLocation.h
  SmartDeviceLink/SDLSendLocation.m
  SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLSendLocationSpec.m
Labels: documentation

#1194 Removed SDLBool Protocol from SDLPermissionManager
  SmartDeviceLink/SDLPermissionConstants.h
  SmartDeviceLink/SDLPermissionManager.h
  SmartDeviceLink/SDLPermissionManager.m
  SmartDeviceLinkTests/DevAPISpecs/SDLPermissionsManagerSpec.m
Labels: bug

#1197 Swift 4_2 Update
  Example Apps/Example Swift/AppDelegate.swift
  Example Apps/Example Swift/AudioManager.swift
  Example Apps/Example Swift/ConnectionContainerViewController.swift
  Example Apps/Example Swift/VehicleDataManager.swift
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
Labels: example app

#1201 API cleanup
  SmartDeviceLink/SDLAppServiceData.h
  SmartDeviceLink/SDLAppServiceData.m
  SmartDeviceLink/SDLAppServiceManifest.h
  SmartDeviceLink/SDLAppServiceManifest.m
  SmartDeviceLink/SDLGetAppServiceData.h
  SmartDeviceLink/SDLGetAppServiceData.m
  SmartDeviceLink/SDLManager.m
  SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLGetAppServiceDataSpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLAppServiceDataSpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLAppServiceManifestSpec.m
Labels: best practice

#1205 Clear appServicesCapability in systemCapabilityManager on stop
  SmartDeviceLink/SDLSystemCapabilityManager.m
Labels: bug
