Repository smartdevicelink/sdl_ios, pull requests merged in 2019-06, with the labels that each got.

#1248 iAP transport disconnect cleanup
  Example Apps/Example ObjC/ProxyManager.m
  Example Apps/Example Swift/ProxyManager.swift
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
  SmartDeviceLink/SDLIAPConstants.h
  SmartDeviceLink/SDLIAPConstants.m
  SmartDeviceLink/SDLIAPControlSession.h
  SmartDeviceLink/SDLIAPControlSession.m
  SmartDeviceLink/SDLIAPControlSessionDelegate.h
  SmartDeviceLink/SDLIAPDataSession.h
  SmartDeviceLink/SDLIAPDataSession.m
  SmartDeviceLink/SDLIAPDataSessionDelegate.h
  SmartDeviceLink/SDLIAPSession.h
  SmartDeviceLink/SDLIAPSession.m
  SmartDeviceLink/SDLIAPSessionDelegate.h
  SmartDeviceLink/SDLIAPTransport.h
  SmartDeviceLink/SDLIAPTransport.m
  SmartDeviceLink/SDLLogFileModuleMap.m
  SmartDeviceLink/SDLStreamDelegate.h
  SmartDeviceLink/SDLStreamDelegate.m
  SmartDeviceLinkTests/TransportSpecs/iAP/SDLIAPConstantsSpec.m
  SmartDeviceLinkTests/TransportSpecs/iAP/SDLIAPControlSessionSpec.m
  SmartDeviceLinkTests/TransportSpecs/iAP/SDLIAPDataSessionSpec.m
  SmartDeviceLinkTests/TransportSpecs/iAP/SDLIAPSessionSpec.m
  SmartDeviceLinkTests/TransportSpecs/iAP/SDLIAPTransportSpec.m
Labels: bug

#1293 Fix ChoiceSetManager Bugs
  SmartDeviceLink/SDLChoiceSetManager.m
  SmartDeviceLink/SDLError.h
  SmartDeviceLink/SDLError.m
  SmartDeviceLink/SDLErrorConstants.h
  SmartDeviceLink/SDLPreloadChoicesOperation.m
Labels: bug

#1289 Support Pushing a PCM Audio Data Buffer on SDLAudioStreamManager
  SmartDeviceLink/SDLAudioFile.h
  SmartDeviceLink/SDLAudioFile.m
  SmartDeviceLink/SDLAudioStreamManager.h
  SmartDeviceLink/SDLAudioStreamManager.m
  SmartDeviceLink/SDLAudioStreamManagerDelegate.h
  SmartDeviceLink/SDLStreamingMediaManager.h
  SmartDeviceLinkTests/DevAPISpecs/SDLAudioStreamManagerSpec.m
  SmartDeviceLinkTests/SDLStreamingAudioManagerMock.h
  SmartDeviceLinkTests/SDLStreamingAudioManagerMock.m
Labels: enhancement, proposal

#1286 Fix SDLAudioFile must be public
  SmartDeviceLink-iOS.podspec
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
  SmartDeviceLink.podspec
  SmartDeviceLink/SmartDeviceLink.h
Labels: bug

#1295 Fixed the soft button operation not finishing if no image or text buttons sent
  SmartDeviceLink/SDLSoftButtonReplaceOperation.m
  SmartDeviceLinkTests/SDLSoftButtonReplaceOperationSpec.m
Labels: bug

#1282 Dynamically Update Menu Manager Cells
  SmartDeviceLink-iOS.podspec
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
  SmartDeviceLink.podspec
  SmartDeviceLink/SDLDynamicMenuUpdateAlgorithm.h
  SmartDeviceLink/SDLDynamicMenuUpdateAlgorithm.m
  SmartDeviceLink/SDLDynamicMenuUpdateRunScore.h
  SmartDeviceLink/SDLDynamicMenuUpdateRunScore.m
  SmartDeviceLink/SDLMenuCell.m
  SmartDeviceLink/SDLMenuManager.h
  SmartDeviceLink/SDLMenuManager.m
  SmartDeviceLink/SDLMenuManagerConstants.h
  SmartDeviceLink/SDLScreenManager.h
  SmartDeviceLink/SDLScreenManager.m
  SmartDeviceLink/SmartDeviceLink.h
  SmartDeviceLinkTests/DevAPISpecs/SDLMenuCellSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLMenuManagerSpec.m
  SmartDeviceLinkTests/SDLMenuRunScoreSpec.m
  SmartDeviceLinkTests/SDLMenuUpdateAlgorithmSpec.m
  SmartDeviceLinkTests/TestUtilities/TestConnectionManager.h
  SmartDeviceLinkTests/TestUtilities/TestConnectionManager.m
Labels: enhancement, proposal

#1303 Fixed Cocoapods not working
  SmartDeviceLink-iOS.podspec
  SmartDeviceLink.podspec
Labels: bug

#1307 Fix `runScore` being a property and several method / variable names
  SmartDeviceLink/SDLMenuManager.m
  SmartDeviceLinkTests/SDLSystemCapabilityManagerSpec.m
Labels: best practice

#1309 Fix crash in preload if there's no handler and the preload fails
  SmartDeviceLink/SDLChoiceSetManager.m
Labels: bug

#1314 Fix/make reference to primaryProtocol to strong
  SmartDeviceLink/SDLSecondaryTransportManager.m
Labels: bug

#1313 Cell Icons do not show up on first menu set
  SmartDeviceLink/SDLMenuManager.m
  SmartDeviceLinkTests/DevAPISpecs/SDLMenuManagerSpec.m
Labels: bug

#1317 Fixed session creation failing due to no background task
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
  SmartDeviceLink/SDLBackgroundTaskManager.h
  SmartDeviceLink/SDLBackgroundTaskManager.m
  SmartDeviceLink/SDLIAPTransport.m
  SmartDeviceLink/SDLLifecycleManager.m
  SmartDeviceLink/SDLProxy.m
Labels: bug

#1322 add nil check of eaSession at SDLIAPDataSession#startSession
  SmartDeviceLink/SDLIAPDataSession.m
Labels: bug
