Repository smartdevicelink/sdl_ios, pull requests merged in 2019-10, with the labels that each got.

#1421 Update some RPC response params to be optional
  SmartDeviceLink/SDLDiagnosticMessageResponse.h
  SmartDeviceLink/SDLDiagnosticMessageResponse.m
  SmartDeviceLink/SDLGetDTCsResponse.h
  SmartDeviceLink/SDLGetDTCsResponse.m
  SmartDeviceLink/SDLGetInteriorVehicleDataResponse.h
  SmartDeviceLink/SDLGetInteriorVehicleDataResponse.m
  SmartDeviceLink/SDLGetSystemCapabilityResponse.h
  SmartDeviceLink/SDLGetSystemCapabilityResponse.m
  SmartDeviceLink/SDLSetInteriorVehicleDataResponse.h
  SmartDeviceLink/SDLSetInteriorVehicleDataResponse.m
Labels: bug

#1426 Making Lockscreen fullscreen for iOS 13
  SmartDeviceLink/Assets/Base.lproj/SDLLockScreen.storyboard
Labels: bug

#1425 Add missing params to HMICapabilities
  SmartDeviceLink/SDLHMICapabilities.h
  SmartDeviceLink/SDLHMICapabilities.m
  SmartDeviceLink/SDLRPCParameterNames.h
  SmartDeviceLink/SDLRPCParameterNames.m
Labels: bug

#1429 Update travis yml for Xcode 11 and fixed failing tests
  .travis.yml
  SmartDeviceLinkTests/DevAPISpecs/SDLMenuManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLPresentKeyboardOperationSpec.m
  SmartDeviceLinkTests/ReferenceImages_64/SDLLockScreenViewControllerSnapshotTests/testAppAndVehicleIcons@2x.png
  SmartDeviceLinkTests/ReferenceImages_64/SDLLockScreenViewControllerSnapshotTests/testLightBackgroundNoAppNoVehicleIcons@2x.png
  SmartDeviceLinkTests/ReferenceImages_64/SDLLockScreenViewControllerSnapshotTests/testNoAppNoVehicleIcons@2x.png
  SmartDeviceLinkTests/ReferenceImages_64/SDLLockScreenViewControllerSnapshotTests/testOnlyAppIcon@2x.png
  SmartDeviceLinkTests/ReferenceImages_64/SDLLockScreenViewControllerSnapshotTests/testOnlyVehicleIcon@2x.png
  SmartDeviceLinkTests/SDLAsynchronousRPCOperationSpec.m
Labels: bug

#1413 Fix Bitrate Update for Video Streaming
  SmartDeviceLink/SDLStreamingMediaConfiguration.h
  SmartDeviceLink/SDLStreamingMediaConfiguration.m
  SmartDeviceLink/SDLStreamingVideoLifecycleManager.h
  SmartDeviceLink/SDLStreamingVideoLifecycleManager.m
  SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m
Labels: bug

#1427 Implement SDL-0243 Manager Update for DisplayCapability
  Example Apps/Example ObjC/MenuManager.m
  Example Apps/Example ObjC/ProxyManager.m
  Example Apps/Example Swift/MenuManager.swift
  Example Apps/Example Swift/ProxyManager.swift
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
  SmartDeviceLink/SDLChoiceSetManager.h
  SmartDeviceLink/SDLChoiceSetManager.m
  SmartDeviceLink/SDLDisplayCapabilities+ShowManagerExtensions.h
  SmartDeviceLink/SDLLifecycleManager.m
  SmartDeviceLink/SDLLogFileModuleMap.m
  SmartDeviceLink/SDLMenuManager.h
  SmartDeviceLink/SDLMenuManager.m
  SmartDeviceLink/SDLPreloadChoicesOperation.h
  SmartDeviceLink/SDLPreloadChoicesOperation.m
  SmartDeviceLink/SDLScreenManager.h
  SmartDeviceLink/SDLScreenManager.m
  SmartDeviceLink/SDLSoftButtonManager.h
  SmartDeviceLink/SDLSoftButtonManager.m
  SmartDeviceLink/SDLSoftButtonReplaceOperation.m
  SmartDeviceLink/SDLSystemCapability.h
  SmartDeviceLink/SDLSystemCapability.m
  SmartDeviceLink/SDLSystemCapabilityManager.h
  SmartDeviceLink/SDLSystemCapabilityManager.m
  SmartDeviceLink/SDLSystemCapabilityObserver.m
  SmartDeviceLink/SDLTextAndGraphicManager.h
  SmartDeviceLink/SDLTextAndGraphicManager.m
  SmartDeviceLink/SDLWindowCapability+ShowManagerExtensions.h
  SmartDeviceLink/SDLWindowCapability+ShowManagerExtensions.m
  SmartDeviceLink/SDLWindowCapability.m
  SmartDeviceLinkTests/DevAPISpecs/SDLChoiceSetManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLFileManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLMenuManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLPreloadChoicesOperationSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLSoftButtonManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLTextAndGraphicManagerSpec.m
  SmartDeviceLinkTests/SDLScreenManagerSpec.m
  SmartDeviceLinkTests/SDLSoftButtonReplaceOperationSpec.m
  SmartDeviceLinkTests/SDLSystemCapabilityManagerSpec.m
Labels: enhancement, proposal

#1420 Implement SDL 0179 - Pixel Density and Scale
  SmartDeviceLink-iOS.podspec
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
  SmartDeviceLink.podspec
  SmartDeviceLink/SDLCarWindow.h
  SmartDeviceLink/SDLCarWindow.m
  SmartDeviceLink/SDLFocusableItemLocator.h
  SmartDeviceLink/SDLFocusableItemLocator.m
  SmartDeviceLink/SDLFocusableItemLocatorType.h
  SmartDeviceLink/SDLRPCParameterNames.h
  SmartDeviceLink/SDLRPCParameterNames.m
  SmartDeviceLink/SDLStreamingMediaManager.h
  SmartDeviceLink/SDLStreamingMediaManager.m
  SmartDeviceLink/SDLStreamingMediaManagerConstants.h
  SmartDeviceLink/SDLStreamingMediaManagerConstants.m
  SmartDeviceLink/SDLStreamingVideoLifecycleManager.h
  SmartDeviceLink/SDLStreamingVideoLifecycleManager.m
  SmartDeviceLink/SDLStreamingVideoScaleManager.h
  SmartDeviceLink/SDLStreamingVideoScaleManager.m
  SmartDeviceLink/SDLTouchManager.h
  SmartDeviceLink/SDLTouchManager.m
  SmartDeviceLink/SDLVideoStreamingCapability.h
  SmartDeviceLink/SDLVideoStreamingCapability.m
  SmartDeviceLink/SmartDeviceLink.h
  SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m
  SmartDeviceLinkTests/ProxySpecs/SDLHapticManagerSpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLSystemCapabilitySpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLVideoStreamingCapabilitySpec.m
  SmartDeviceLinkTests/SDLStreamingVideoScaleManagerSpec.m
  SmartDeviceLinkTests/UtilitiesSpecs/Touches/SDLTouchManagerSpec.m
Labels: proposal

#1347 Implement SDL-0231 Main Menu Tiles
  Example Apps/Example ObjC/MenuManager.m
  Example Apps/Example Swift/MenuManager.swift
  SmartDeviceLink-iOS.podspec
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
  SmartDeviceLink.podspec
  SmartDeviceLink/SDLAddSubMenu.h
  SmartDeviceLink/SDLAddSubMenu.m
  SmartDeviceLink/SDLMenuCell.h
  SmartDeviceLink/SDLMenuCell.m
  SmartDeviceLink/SDLMenuConfiguration.h
  SmartDeviceLink/SDLMenuConfiguration.m
  SmartDeviceLink/SDLMenuLayout.h
  SmartDeviceLink/SDLMenuLayout.m
  SmartDeviceLink/SDLMenuManager.h
  SmartDeviceLink/SDLMenuManager.m
  SmartDeviceLink/SDLRPCParameterNames.h
  SmartDeviceLink/SDLRPCParameterNames.m
  SmartDeviceLink/SDLScreenManager.h
  SmartDeviceLink/SDLScreenManager.m
  SmartDeviceLink/SDLSetGlobalProperties.h
  SmartDeviceLink/SDLSetGlobalProperties.m
  SmartDeviceLink/SDLWindowCapability.h
  SmartDeviceLink/SDLWindowCapability.m
  SmartDeviceLink/SmartDeviceLink.h
  SmartDeviceLinkTests/DevAPISpecs/SDLMenuCellSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLMenuConfigurationSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLMenuManagerSpec.m
  SmartDeviceLinkTests/RPCSpecs/EnumSpecs/SDLMenuLayoutSpec.m
  SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLAddSubMenuSpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLDisplayCapabilitiesSpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLDisplayCapabilitySpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLWindowCapabilitySpec.m
Labels: enhancement, proposal

#1320 Implement SDL-0207 RPC Message Protection
  SmartDeviceLink-iOS.podspec
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
  SmartDeviceLink.podspec
  SmartDeviceLink/SDLConfiguration.h
  SmartDeviceLink/SDLConfiguration.m
  SmartDeviceLink/SDLEncryptionConfiguration.h
  SmartDeviceLink/SDLEncryptionConfiguration.m
  SmartDeviceLink/SDLEncryptionLifecycleManager.h
  SmartDeviceLink/SDLEncryptionLifecycleManager.m
  SmartDeviceLink/SDLEncryptionManagerConstants.h
  SmartDeviceLink/SDLEncryptionManagerConstants.m
  SmartDeviceLink/SDLError.h
  SmartDeviceLink/SDLError.m
  SmartDeviceLink/SDLErrorConstants.h
  SmartDeviceLink/SDLLifecycleManager.h
  SmartDeviceLink/SDLLifecycleManager.m
  SmartDeviceLink/SDLLogFileModuleMap.m
  SmartDeviceLink/SDLManager.h
  SmartDeviceLink/SDLManager.m
  SmartDeviceLink/SDLOnPermissionsChange.h
  SmartDeviceLink/SDLOnPermissionsChange.m
  SmartDeviceLink/SDLPermissionItem.h
  SmartDeviceLink/SDLPermissionItem.m
  SmartDeviceLink/SDLPermissionManager.h
  SmartDeviceLink/SDLPermissionManager.m
  SmartDeviceLink/SDLProtocol.h
  SmartDeviceLink/SDLProtocol.m
  SmartDeviceLink/SDLProtocolMessage.m
  SmartDeviceLink/SDLProxy.h
  SmartDeviceLink/SDLProxy.m
  SmartDeviceLink/SDLRPCParameterNames.h
  SmartDeviceLink/SDLRPCParameterNames.m
  SmartDeviceLink/SDLRPCStruct.h
  SmartDeviceLink/SDLRPCStruct.m
  SmartDeviceLink/SDLResult.h
  SmartDeviceLink/SDLResult.m
  SmartDeviceLink/SDLServiceEncryptionDelegate.h
  SmartDeviceLink/SDLStreamingAudioLifecycleManager.h
  SmartDeviceLink/SDLStreamingAudioLifecycleManager.m
  SmartDeviceLink/SDLStreamingMediaConfiguration.h
  SmartDeviceLink/SDLStreamingMediaConfiguration.m
  SmartDeviceLink/SDLStreamingMediaManager.m
  SmartDeviceLink/SDLStreamingVideoLifecycleManager.m
  SmartDeviceLink/SmartDeviceLink.h
  SmartDeviceLinkTests/DevAPISpecs/SDLConfigurationSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLLifecycleManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLPermissionsManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLStreamingAudioLifecycleManagerSpec.m
  SmartDeviceLinkTests/RPCSpecs/EnumSpecs/SDLResultSpec.m
  SmartDeviceLinkTests/RPCSpecs/NotificationSpecs/SDLOnPermissionsChangeSpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLPermissionItemSpec.m
  SmartDeviceLinkTests/SDLEncryptionConfigurationSpec.m
  SmartDeviceLinkTests/SDLEncryptionLifecycleManagerSpec.m
Labels: enhancement, proposal

#1435 Add a check before popping the mutable data queue buffer
  SmartDeviceLink/SDLMutableDataQueue.m
Labels: bug

#1438 Fixed Swift Example app not compiling
  Example Apps/Example Swift/MenuManager.swift
Labels: bug, example app

#1440 Add additional type information in assert
  SmartDeviceLink/NSMutableDictionary+Store.m
Labels: best practice

#1444 Fix some RemoteControlCapabilities parameters having the wrong type
  SmartDeviceLink/SDLRemoteControlCapabilities.m
Labels: bug

#1447 Don't create the encryption lifecycle manager if it won't be used
  SmartDeviceLink/SDLLifecycleManager.m
  SmartDeviceLink/SDLTextAndGraphicManager.m
Labels: bug

#1448 The displays property is now reset when system capability manager is stopped
  SmartDeviceLink/SDLSystemCapabilityManager.m
  SmartDeviceLinkTests/DevAPISpecs/SDLMenuManagerSpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLRemoteControlCapabilitiesSpec.m
Labels: bug

#1443 Update vehicle data RPCs' generic data getters to return nullable
  SmartDeviceLink/SDLGetVehicleData.h
  SmartDeviceLink/SDLGetVehicleData.m
  SmartDeviceLink/SDLGetVehicleDataResponse.h
  SmartDeviceLink/SDLGetVehicleDataResponse.m
  SmartDeviceLink/SDLOnVehicleData.h
  SmartDeviceLink/SDLOnVehicleData.m
  SmartDeviceLink/SDLSubscribeVehicleData.h
  SmartDeviceLink/SDLSubscribeVehicleData.m
  SmartDeviceLink/SDLSubscribeVehicleDataResponse.h
  SmartDeviceLink/SDLSubscribeVehicleDataResponse.m
  SmartDeviceLink/SDLUnsubscribeVehicleData.h
  SmartDeviceLink/SDLUnsubscribeVehicleData.m
  SmartDeviceLink/SDLUnsubscribeVehicleDataResponse.h
  SmartDeviceLink/SDLUnsubscribeVehicleDataResponse.m
Labels: bug

#1452 Added payload encrypted description
  SmartDeviceLink/SDLProtocolMessage.m
  SmartDeviceLinkTests/SDLStreamingVideoScaleManagerSpec.m
  SmartDeviceLinkTests/UtilitiesSpecs/Touches/SDLTouchManagerSpec.m
Labels: best practice

#1453 Only sessions with same connectionID as the disconnected accessory should be closed
  SmartDeviceLink/SDLIAPTransport.m
Labels: bug

#1458 Fix wording in warning messages
  SmartDeviceLink/SDLLifecycleManager.m
Labels: bug

#1459 Change example app resultCode check to the success bool instead
  Example Apps/Example ObjC/MenuManager.m
  Example Apps/Example Swift/MenuManager.swift
Labels: bug, example app

#1436 Deprecated warnings in tests
  SmartDeviceLinkTests/DevAPISpecs/SDLStreamingMediaConfigurationSpec.m
  SmartDeviceLinkTests/ProtocolSpecs/MessageSpecs/SDLProtocolSpec.m
  SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLButtonPressSpec.m
  SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLGetInteriorVehicleDataSpec.m
  SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLShowSpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLClimateControlCapabilitiesSpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLDisplayCapabilitiesSpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLRadioControlCapabilitiesSpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLSyncMsgVersionSpec.m
  SmartDeviceLinkTests/SDLSystemCapabilityManagerSpec.m
Labels: best practice

#1460 Fixed failing iAP transport test cases
  SmartDeviceLinkTests/TransportSpecs/iAP/SDLIAPTransportSpec.m
Labels: bug

#1455 Keep File Manager from Error State on disallowed
  SmartDeviceLink/SDLFileManager.m
  SmartDeviceLink/SDLListFilesOperation.m
  SmartDeviceLinkTests/DevAPISpecs/SDLFileManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLListFilesOperationSpec.m
Labels: bug

#1463 Revert removing the data session delay
  SmartDeviceLink/SDLIAPDataSession.m
  SmartDeviceLink/SDLIAPTransport.m
Labels: bug
