Repository smartdevicelink/sdl_ios, pull requests merged in 2019-04, with the labels that each got.

#1209 Hit test for a single tap now checked on main thread
  SmartDeviceLink/SDLFocusableItemLocator.m
  SmartDeviceLink/SDLTouchManager.m
  SmartDeviceLinkTests/ProxySpecs/SDLHapticManagerSpec.m
Labels: bug

#1213 Update documentation to warn the devs to wrap a `stop` call in `start:withReadyHandler:`
  SmartDeviceLink/SDLLifecycleManager.h
Labels: documentation

#1219 Add missing `SDLAppInterfaceUnregisteredReason`
  SmartDeviceLink/SDLAppInterfaceUnregisteredReason.h
  SmartDeviceLink/SDLAppInterfaceUnregisteredReason.m
  SmartDeviceLinkTests/RPCSpecs/EnumSpecs/SDLAppInterfaceUnregisteredReasonSpec.m
Labels: bug

#1211 Update test dependencies for Xcode 10.2
  .travis.yml
  Cartfile.private
  Cartfile.resolved
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
  SmartDeviceLinkTests/ProtocolSpecs/MessageSpecs/SDLV1ProtocolMessageSpec.m
Labels: bug, distribution

#1223 Adding missing conditional check to stop the manager if SDLAppInterfa…
  SmartDeviceLink/SDLLifecycleManager.m
  SmartDeviceLinkTests/DevAPISpecs/SDLLifecycleManagerSpec.m
Labels: bug

#1226 Removed check for class type
  SmartDeviceLink/SDLLifecycleManager.m
Labels: bug

#1215 Update System Capability Manager to auto-cache`OnSystemCapability`
  SmartDeviceLink/SDLSystemCapabilityManager.m
  SmartDeviceLinkTests/SDLSystemCapabilityManagerSpec.m
Labels: enhancement

#1225 Update `lastCorrelationId` to be Int32 instead of UInt16
  SmartDeviceLink/SDLLifecycleManager.h
  SmartDeviceLink/SDLLifecycleManager.m
  SmartDeviceLinkTests/DevAPISpecs/SDLLifecycleManagerSpec.m
  SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLAlertSpec.m
Labels: bug

#1231 Add a toggle for disabling bad data assertions
  SmartDeviceLink/NSMutableDictionary+Store.m
  SmartDeviceLink/SDLLogConfiguration.h
  SmartDeviceLink/SDLLogConfiguration.m
  SmartDeviceLink/SDLLogMacros.h
  SmartDeviceLink/SDLLogManager.h
  SmartDeviceLink/SDLLogManager.m
  SmartDeviceLinkTests/LoggingSpecs/SDLLogConfigurationSpec.m
Labels: bug, enhancement

#1228 Choice set manager should return nil if there's no menu name
  SmartDeviceLink/SDLError.h
  SmartDeviceLink/SDLError.m
  SmartDeviceLink/SDLErrorConstants.h
  SmartDeviceLink/SDLPreloadChoicesOperation.m
  SmartDeviceLinkTests/DevAPISpecs/SDLPreloadChoicesOperationSpec.m
Labels: bug

#1232 Fixing issue that caused SDLTransportDidDisconnect to get called befo…
  SmartDeviceLink/SDLProxy.m
Labels: bug

#1235 Audio stream manager no longer suspends audio when device app is inactive
  SmartDeviceLink/SDLStreamingAudioLifecycleManager.h
  SmartDeviceLink/SDLStreamingAudioLifecycleManager.m
  SmartDeviceLinkTests/DevAPISpecs/SDLStreamingAudioLifecycleManagerSpec.m
Labels: bug

#1246 Updating project and example app to swift 5.0
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
Labels: enhancement, example app

#1242 Fixed alert documentation
  SmartDeviceLink/SDLAlert.h
Labels: bug
