Repository smartdevicelink/sdl_ios, pull requests merged in 2019-05, with the labels that each got.

#1236 Ignore Errant Connections While Reconnecting
  SmartDeviceLink/SDLLifecycleManager.m
Labels: bug

#1244 Fix auto-reconnect / manual disconnect of example apps
  Example Apps/Example ObjC/ConnectionIAPTableViewController.m
  Example Apps/Example ObjC/ConnectionTCPTableViewController.m
  Example Apps/Example ObjC/ProxyManager.h
  Example Apps/Example ObjC/ProxyManager.m
  Example Apps/Example Swift/ConnectionIAPTableViewController.swift
  Example Apps/Example Swift/ConnectionTCPTableViewController.swift
  Example Apps/Example Swift/ProxyManager.swift
  Example Apps/Example Swift/ProxyManagerDelegate.swift
  Example Apps/Shared/AppConstants.m
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
Labels: bug, example app

#1252 Fix Lockscreen Window's Existence Messing with App Autorotation
  SmartDeviceLink/SDLScreenshotViewController.m
Labels: bug

#1256 Throw an exception if SDL is setup before the app's root view controller
  SmartDeviceLink/SDLError.h
  SmartDeviceLink/SDLError.m
  SmartDeviceLink/SDLScreenshotViewController.m
Labels: bug

#1259 Fix all crashes due to lockscreen being setup before app window
  SmartDeviceLink/SDLScreenshotViewController.m
Labels: bug

#1267 IAP Transport / Sessions Cleanup
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
  SmartDeviceLink/SDLIAPControlSession.h
  SmartDeviceLink/SDLIAPControlSession.m
  SmartDeviceLink/SDLIAPControlSessionDelegate.h
  SmartDeviceLink/SDLIAPDataSession.h
  SmartDeviceLink/SDLIAPDataSession.m
  SmartDeviceLink/SDLIAPSession.h
  SmartDeviceLink/SDLIAPSession.m
  SmartDeviceLink/SDLIAPSessionDelegate.h
  SmartDeviceLink/SDLIAPTransport.m
  SmartDeviceLink/SDLStreamDelegate.h
  SmartDeviceLink/SDLStreamDelegate.m
  SmartDeviceLinkTests/TransportSpecs/iAP/SDLIAPSessionSpec.m
Labels: best practice, bug, enhancement

#1251 Fix SoftButtonManager Race Conditions
  Example Apps/Example ObjC/ButtonManager.m
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
  SmartDeviceLink/SDLAsynchronousOperation.h
  SmartDeviceLink/SDLChoiceSetManager.m
  SmartDeviceLink/SDLLogFileModuleMap.m
  SmartDeviceLink/SDLScreenManager.m
  SmartDeviceLink/SDLSoftButtonManager.h
  SmartDeviceLink/SDLSoftButtonManager.m
  SmartDeviceLink/SDLSoftButtonReplaceOperation.h
  SmartDeviceLink/SDLSoftButtonReplaceOperation.m
  SmartDeviceLink/SDLSoftButtonTransitionOperation.h
  SmartDeviceLink/SDLSoftButtonTransitionOperation.m
  SmartDeviceLinkTests/DevAPISpecs/SDLSoftButtonManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLSoftButtonTransitionOperationSpec.m
  SmartDeviceLinkTests/SDLScreenManagerSpec.m
  SmartDeviceLinkTests/SDLSoftButtonReplaceOperationSpec.m
Labels: bug

#1271 Implement SDL-0226: SDLManager RPC Subscription Helper Methods
  Example Apps/Example ObjC/VehicleDataManager.m
  Example Apps/Example Swift/VehicleDataManager.swift
  SmartDeviceLink/SDLManager.h
  SmartDeviceLink/SDLManager.m
Labels: enhancement

#1273 SwiftPM/Accio Support
  Package.swift
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
Labels: distribution

#1277 Fixed file manager race condition
  SmartDeviceLink/SDLFileManager.m
  SmartDeviceLinkTests/DevAPISpecs/SDLFileManagerSpec.m
Labels: bug

#1279 Support SDLSystemCapabilityManager Subscriptions
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
  SmartDeviceLink/SDLError.h
  SmartDeviceLink/SDLError.m
  SmartDeviceLink/SDLLifecycleManager.m
  SmartDeviceLink/SDLSystemCapabilityManager.h
  SmartDeviceLink/SDLSystemCapabilityManager.m
  SmartDeviceLink/SDLSystemCapabilityObserver.h
  SmartDeviceLink/SDLSystemCapabilityObserver.m
  SmartDeviceLinkTests/DevAPISpecs/TestSystemCapabilityObserver.h
  SmartDeviceLinkTests/DevAPISpecs/TestSystemCapabilityObserver.m
  SmartDeviceLinkTests/SDLSystemCapabilityManagerSpec.m
Labels: best practice, enhancement

#1292 Fix position not being set on SDLChoiceSet VRHelpList
  SmartDeviceLink/SDLChoiceSet.m
  SmartDeviceLinkTests/DevAPISpecs/SDLChoiceSetSpec.m
Labels: bug

#1287 Prevent Buffer Overruns
  SmartDeviceLink/SDLControlFramePayloadAudioStartServiceAck.m
  SmartDeviceLink/SDLControlFramePayloadEndService.m
  SmartDeviceLink/SDLControlFramePayloadNak.m
  SmartDeviceLink/SDLControlFramePayloadRPCStartService.m
  SmartDeviceLink/SDLControlFramePayloadRPCStartServiceAck.m
  SmartDeviceLink/SDLControlFramePayloadRegisterSecondaryTransportNak.m
  SmartDeviceLink/SDLControlFramePayloadTransportEventUpdate.m
  SmartDeviceLink/SDLControlFramePayloadVideoStartService.m
  SmartDeviceLink/SDLControlFramePayloadVideoStartServiceAck.m
Labels: bug
