Repository smartdevicelink/sdl_ios, pull requests merged in 2019-09, with the labels that each got.

#1346 Implement SDL-0184 CancelInteraction RPC
  Example Apps/Example ObjC/AlertManager.h
  Example Apps/Example ObjC/AlertManager.m
  Example Apps/Example Swift/AlertManager.swift
  Example Apps/Example Swift/VehicleDataManager.swift
  Example Apps/Shared/AppConstants.h
  Example Apps/Shared/AppConstants.m
  SmartDeviceLink-iOS.podspec
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
  SmartDeviceLink.podspec
  SmartDeviceLink/SDLAlert.h
  SmartDeviceLink/SDLAlert.m
  SmartDeviceLink/SDLCancelInteraction.h
  SmartDeviceLink/SDLCancelInteraction.m
  SmartDeviceLink/SDLCancelInteractionResponse.h
  SmartDeviceLink/SDLCancelInteractionResponse.m
  SmartDeviceLink/SDLChoiceSet.h
  SmartDeviceLink/SDLChoiceSet.m
  SmartDeviceLink/SDLChoiceSetManager.h
  SmartDeviceLink/SDLChoiceSetManager.m
  SmartDeviceLink/SDLFunctionID.m
  SmartDeviceLink/SDLLifecycleManager.m
  SmartDeviceLink/SDLNotificationConstants.h
  SmartDeviceLink/SDLNotificationConstants.m
  SmartDeviceLink/SDLNotificationDispatcher.m
  SmartDeviceLink/SDLPerformInteraction.h
  SmartDeviceLink/SDLPerformInteraction.m
  SmartDeviceLink/SDLPresentChoiceSetOperation.h
  SmartDeviceLink/SDLPresentChoiceSetOperation.m
  SmartDeviceLink/SDLPresentKeyboardOperation.h
  SmartDeviceLink/SDLPresentKeyboardOperation.m
  SmartDeviceLink/SDLProxyListener.h
  SmartDeviceLink/SDLRPCFunctionNames.h
  SmartDeviceLink/SDLRPCFunctionNames.m
  SmartDeviceLink/SDLRPCParameterNames.h
  SmartDeviceLink/SDLRPCParameterNames.m
  SmartDeviceLink/SDLScreenManager.h
  SmartDeviceLink/SDLScreenManager.m
  SmartDeviceLink/SDLScrollableMessage.h
  SmartDeviceLink/SDLScrollableMessage.m
  SmartDeviceLink/SDLSlider.h
  SmartDeviceLink/SDLSlider.m
  SmartDeviceLink/SmartDeviceLink.h
  SmartDeviceLinkTests/DevAPISpecs/SDLChoiceSetManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLChoiceSetSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLPresentChoiceSetOperationSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLPresentKeyboardOperationSpec.m
  SmartDeviceLinkTests/Notifications/SDLResponseDispatcherSpec.m
  SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLAlertSpec.m
  SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLCancelInteractionSpec.m
  SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLPerformInteractionSpec.m
  SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLScrollableMessageSpec.m
  SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLSliderSpec.m
  SmartDeviceLinkTests/RPCSpecs/ResponseSpecs/SDLCancelInteractionResponseSpec.m
  SmartDeviceLinkTests/SDLRPCFunctionNamesSpec.m
Labels: enhancement, proposal

#1397 SystemCapabilityManager fails to support SeatLocation capability
  SmartDeviceLink/SDLSystemCapabilityManager.m
  SmartDeviceLinkTests/SDLSystemCapabilityManagerSpec.m
Labels: bug

#1398 Add remoteControl to HMICapabilities
  SmartDeviceLink/SDLHMICapabilities.h
  SmartDeviceLink/SDLHMICapabilities.m
  SmartDeviceLink/SDLRPCParameterNames.h
  SmartDeviceLink/SDLRPCParameterNames.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLHMICapabilitiesSpec.m
Labels: bug

#1400 Updating travis.yml to use iOS 12.4
  .travis.yml
  SmartDeviceLink/SDLLockScreenConfiguration.m
  SmartDeviceLinkTests/DevAPISpecs/SDLFileManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLLockScreenConfigurationSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLMenuManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLPresentKeyboardOperationSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m
  SmartDeviceLinkTests/ReferenceImages_64/SDLLockScreenViewControllerSnapshotTests/testAppAndVehicleIcons@2x.png
  SmartDeviceLinkTests/ReferenceImages_64/SDLLockScreenViewControllerSnapshotTests/testAppAndVehicleIcons_iPhone11_4_0x0@3x.png
  SmartDeviceLinkTests/ReferenceImages_64/SDLLockScreenViewControllerSnapshotTests/testLightBackgroundNoAppNoVehicleIcons@2x.png
  SmartDeviceLinkTests/ReferenceImages_64/SDLLockScreenViewControllerSnapshotTests/testLightBackgroundNoAppNoVehicleIcons_iPhone11_4_0x0@3x.png
  SmartDeviceLinkTests/ReferenceImages_64/SDLLockScreenViewControllerSnapshotTests/testNoAppNoVehicleIcons@2x.png
  SmartDeviceLinkTests/ReferenceImages_64/SDLLockScreenViewControllerSnapshotTests/testNoAppNoVehicleIcons_iPhone11_4_0x0@3x.png
  SmartDeviceLinkTests/ReferenceImages_64/SDLLockScreenViewControllerSnapshotTests/testOnlyAppIcon@2x.png
  SmartDeviceLinkTests/ReferenceImages_64/SDLLockScreenViewControllerSnapshotTests/testOnlyAppIcon_iPhone11_4_0x0@3x.png
  SmartDeviceLinkTests/ReferenceImages_64/SDLLockScreenViewControllerSnapshotTests/testOnlyVehicleIcon@2x.png
  SmartDeviceLinkTests/ReferenceImages_64/SDLLockScreenViewControllerSnapshotTests/testOnlyVehicleIcon_iPhone11_4_0x0@3x.png
  SmartDeviceLinkTests/SDLAsynchronousRPCOperationSpec.m
Labels: bug, distribution

#1393 reflect bitrate returned from HMI in video encoder settings
  SmartDeviceLink/SDLStreamingMediaConfiguration.h
  SmartDeviceLink/SDLStreamingMediaConfiguration.m
  SmartDeviceLink/SDLStreamingVideoLifecycleManager.h
  SmartDeviceLink/SDLStreamingVideoLifecycleManager.m
  SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m
Labels: bug

#1403 Update SDLAsynchronousOperation subclasses to abort on start if they're cancelled
  SmartDeviceLink/SDLAsynchronousRPCOperation.m
  SmartDeviceLink/SDLAsynchronousRPCRequestOperation.m
  SmartDeviceLink/SDLCheckChoiceVROptionalOperation.m
  SmartDeviceLink/SDLDeleteChoicesOperation.m
  SmartDeviceLink/SDLDeleteFileOperation.m
  SmartDeviceLink/SDLListFilesOperation.m
  SmartDeviceLink/SDLPreloadChoicesOperation.m
  SmartDeviceLink/SDLPresentChoiceSetOperation.m
  SmartDeviceLink/SDLPresentKeyboardOperation.m
  SmartDeviceLink/SDLSequentialRPCRequestOperation.m
  SmartDeviceLink/SDLSoftButtonReplaceOperation.m
  SmartDeviceLink/SDLSoftButtonTransitionOperation.m
  SmartDeviceLink/SDLUploadFileOperation.m
  SmartDeviceLinkTests/DevAPISpecs/SDLPresentKeyboardOperationSpec.m
Labels: best practice, bug

#1416 Remove duplicate SDLGetDTCsSpec.m from build
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
Labels: bug

#1415 changing inits to class methods to fix swift formatting issues
  SmartDeviceLink/SDLCancelInteraction.h
  SmartDeviceLink/SDLCancelInteraction.m
  SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLCancelInteractionSpec.m
Labels: bug, enhancement

#1412 Streamingvideolifecyclemanagers is streaming supported
  SmartDeviceLink/SDLStreamingVideoLifecycleManager.m
  SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m
Labels: bug

#1405 Slider/Scrollable Message Alert if unsupported
  Example Apps/Example ObjC/MenuManager.m
  Example Apps/Example Swift/MenuManager.swift
Labels: bug

#1418 Add HMICapabilities.appServices parameter
  Cartfile.resolved
  SmartDeviceLink/SDLHMICapabilities.h
  SmartDeviceLink/SDLHMICapabilities.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLHMICapabilitiesSpec.m
Labels: enhancement, proposal
