Repository smartdevicelink/sdl_ios, pull requests merged in 2020-01, with the labels that each got.

#1495 Only try to remove from run loop when we aren't closing
  SmartDeviceLink/SDLIAPSession.m
Labels: bug

#1489 Fixed the Show RPC's templateConfiguration parameter not getting set
  SmartDeviceLink/SDLShow.m
  SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLShowSpec.m
Labels: bug

#1485 Add APIs to SDLTemplateConfiguration for Objective-C++ compatibility
  SmartDeviceLink/SDLTemplateConfiguration.h
  SmartDeviceLink/SDLTemplateConfiguration.m
Labels: bug

#1484 Fixed soft button operation never finishing if template does not support soft buttons
  SmartDeviceLink/SDLSoftButtonReplaceOperation.m
  SmartDeviceLinkTests/SDLSoftButtonReplaceOperationSpec.m
Labels: bug

#1467 Fix SystemCapabilityManager subscribe not returning the correct type
  SmartDeviceLink/SDLSystemCapabilityManager.m
Labels: bug

#1509 Lockscreen bug fixes
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
  SmartDeviceLink/SDLLockScreenManager.h
  SmartDeviceLink/SDLLockScreenManager.m
  SmartDeviceLink/SDLLockScreenPresenter.h
  SmartDeviceLink/SDLLockScreenPresenter.m
  SmartDeviceLink/SDLLockScreenRootViewController.h
  SmartDeviceLink/SDLLockScreenRootViewController.m
  SmartDeviceLink/SDLManager.m
  SmartDeviceLink/SDLScreenshotViewController.h
  SmartDeviceLink/SDLScreenshotViewController.m
  SmartDeviceLink/SDLViewControllerPresentable.h
  SmartDeviceLinkTests/DevAPISpecs/SDLFakeViewControllerPresenter.h
  SmartDeviceLinkTests/DevAPISpecs/SDLFakeViewControllerPresenter.m
  SmartDeviceLinkTests/DevAPISpecs/SDLLockScreenManagerSpec.m
Labels: bug

#1482 Security manager set for secondary protocol
  SmartDeviceLink/SDLSecondaryTransportManager.m
  SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m
Labels: bug

#1518 Fix issues shown by OCMock 3.5
  SmartDeviceLinkTests/DevAPISpecs/SDLChoiceSetManagerSpec.m
  SmartDeviceLinkTests/ProxySpecs/SDLHapticManagerSpec.m
Labels: bug, testing

#1525 Create XM, AM and FM Convenience inits
  SmartDeviceLink/SDLRadioControlData.h
  SmartDeviceLink/SDLRadioControlData.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLRadioControlDataSpec.m
Labels: best practice, bug

#1530 Lockscreen storyboard warnings
  SmartDeviceLink/Assets/Base.lproj/SDLLockScreen.storyboard
Labels: bug, manager-lockscreen
