Repository smartdevicelink/sdl_ios, pull requests merged in 2020-10, with the labels that each got.

#1803 Fix Github CI and update to Xcode 12 in CI
  .github/workflows/test.yml
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
  SmartDeviceLinkTests/DevAPISpecs/SDLLifecycleManagerSpec.m
  SmartDeviceLinkTests/TransportSpecs/iAP/SDLIAPControlSessionSpec.m
  SmartDeviceLinkTests/TransportSpecs/iAP/SDLIAPDataSessionSpec.m
  SmartDeviceLinkTests/TransportSpecs/iAP/SDLIAPSessionSpec.m
  SmartDeviceLinkTests/TransportSpecs/iAP/SDLIAPTransportSpec.m
  SmartDeviceLinkTests/TransportSpecs/iAP/Utilities/EAAccessory+OCMock.h
  SmartDeviceLinkTests/TransportSpecs/iAP/Utilities/EAAccessory+OCMock.m
  carthage-build.sh
Labels: bug, testing

#1804 Fix random crashes in the unit tests for the SDLLifecycleManager
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
  SmartDeviceLinkTests/DevAPISpecs/SDLAudioStreamManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLLifecycleManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/TestOldConfigurationUpdateManagerDelegate.h
  SmartDeviceLinkTests/DevAPISpecs/TestOldConfigurationUpdateManagerDelegate.m
  SmartDeviceLinkTests/TestNewConfigurationUpdateManagerDelegate.h
  SmartDeviceLinkTests/TestNewConfigurationUpdateManagerDelegate.m
Labels: bug, testing

#1814 Deprecate SetDisplayLayout RPC
  Example Apps/Example ObjC/MenuManager.m
  Example Apps/Example ObjC/ProxyManager.m
  Example Apps/Example Swift/MenuManager.swift
  Example Apps/Example Swift/ProxyManager.swift
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
  SmartDeviceLink-iOS.xcodeproj/xcshareddata/xcschemes/SmartDeviceLink-Example-ObjC.xcscheme
  SmartDeviceLink-iOS.xcodeproj/xcshareddata/xcschemes/SmartDeviceLink.xcscheme
  SmartDeviceLink-iOS.xcodeproj/xcshareddata/xcschemes/SmartDeviceLinkSwift.xcscheme
  SmartDeviceLink/private/SDLTextAndGraphicUpdateOperation.m
  SmartDeviceLink/public/SDLSetDisplayLayout.h
  SmartDeviceLink/public/SDLSetDisplayLayout.m
  SmartDeviceLink/public/SDLSetDisplayLayoutResponse.h
  SmartDeviceLink/public/SDLSetDisplayLayoutResponse.m
  SmartDeviceLinkTests/DevAPISpecs/SDLTextAndGraphicUpdateOperationSpec.m
  SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLSetDisplayLayoutSpec.m
  SmartDeviceLinkTests/RPCSpecs/ResponseSpecs/SDLSetDisplayLayoutResponseSpec.m
  SmartDeviceLinkTests/SDLSystemCapabilityManagerSpec.m
Labels: bug, rpc

#1817 Update README with testing info to look at CI tests
  README.md
Labels: best practice, documentation

#1807 Change SDLLockScreenViewController modalPresentationStyle
  SmartDeviceLink/public/SDLLockScreenViewController.m
Labels: bug, manager-lockscreen

#1822 Add nullable attribute to lockScreenDismissalEnabled and lockScreenDismissalWarning
  SmartDeviceLink/public/SDLOnDriverDistraction.h
  SmartDeviceLink/public/SDLOnDriverDistraction.m
  SmartDeviceLinkTests/RPCSpecs/NotificationSpecs/SDLOnDriverDistractionSpec.m
Labels: bug

#1818 Fix example apps resetting the soft button state when going from HMI BACKGROUND -> FULL
  Example Apps/Example ObjC/ProxyManager.m
  Example Apps/Example Swift/ProxyManager.swift
Labels: bug, example app
