Repository smartdevicelink/sdl_ios, pull requests merged in 2021-03, with the labels that each got.

#1861 SDL 0282 - Alert Manager
  Example Apps/Example ObjC/AlertManager.m
  Example Apps/Example Swift/AlertManager.swift
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
  SmartDeviceLink/private/SDLAlertManager.h
  SmartDeviceLink/private/SDLAlertManager.m
  SmartDeviceLink/private/SDLChoiceSetManager.m
  SmartDeviceLink/private/SDLError.h
  SmartDeviceLink/private/SDLError.m
  SmartDeviceLink/private/SDLLifecycleManager.m
  SmartDeviceLink/private/SDLLogFileModuleMap.m
  SmartDeviceLink/private/SDLMenuManager.m
  SmartDeviceLink/private/SDLPresentAlertOperation.h
  SmartDeviceLink/private/SDLPresentAlertOperation.m
  SmartDeviceLink/private/SDLSoftButtonManager.m
  SmartDeviceLink/private/SDLTextAndGraphicManager.m
  SmartDeviceLink/private/SDLWindowCapability+ScreenManagerExtensions.h
  SmartDeviceLink/private/SDLWindowCapability+ScreenManagerExtensions.m
  SmartDeviceLink/public/SDLAlertAudioData.h
  SmartDeviceLink/public/SDLAlertAudioData.m
  SmartDeviceLink/public/SDLAlertView.h
  SmartDeviceLink/public/SDLAlertView.m
  SmartDeviceLink/public/SDLAudioData.h
  SmartDeviceLink/public/SDLAudioData.m
  SmartDeviceLink/public/SDLErrorConstants.h
  SmartDeviceLink/public/SDLErrorConstants.m
  SmartDeviceLink/public/SDLFileManager.h
  SmartDeviceLink/public/SDLFileManager.m
  SmartDeviceLink/public/SDLScreenManager.h
  SmartDeviceLink/public/SDLScreenManager.m
  SmartDeviceLink/public/SDLSystemCapabilityManager.m
  SmartDeviceLink/public/SmartDeviceLink.h
  SmartDeviceLinkTests/DevAPISpecs/SDLChoiceSetManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLMenuManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLSoftButtonManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLTextAndGraphicManagerSpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLWindowCapabilitySpec.m
  SmartDeviceLinkTests/SDLAlertAudioDataSpec.m
  SmartDeviceLinkTests/SDLAlertManagerSpec.m
  SmartDeviceLinkTests/SDLAlertViewSpec.m
  SmartDeviceLinkTests/SDLAudioDataSpec.m
  SmartDeviceLinkTests/SDLPresentAlertOperationSpec.m
  SmartDeviceLinkTests/SDLScreenManagerSpec.m
Labels: manager-screen, proposal

#1924 Fixed empty string bug in Menu Cell texts
  SmartDeviceLink/private/SDLMenuManager.m
Labels: bug

#1926 Fixed deprecation warning in test workflow file
  .github/workflows/test.yml
Labels: testing

#1932 Updated SDLMenuCell params order
  Example Apps/Example ObjC/MenuManager.m
  Example Apps/Example Swift/MenuManager.swift
  SmartDeviceLink/public/SDLMenuCell.h
  SmartDeviceLink/public/SDLMenuCell.m
  SmartDeviceLinkTests/DevAPISpecs/SDLMenuCellSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLMenuManagerSpec.m
  SmartDeviceLinkTests/SDLMenuUpdateAlgorithmSpec.m
Labels: best practice

#1886 SDL 0180 - Fix to support broaden choice cell uniqueness
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
  SmartDeviceLink/private/NSArray+Extensions.h
  SmartDeviceLink/private/NSArray+Extensions.m
  SmartDeviceLink/private/SDLChoiceSetManager.m
  SmartDeviceLink/private/SDLMacros.h
  SmartDeviceLink/private/SDLMacros.m
  SmartDeviceLink/private/SDLMenuManager.m
  SmartDeviceLink/private/SDLPreloadChoicesOperation.h
  SmartDeviceLink/private/SDLPreloadChoicesOperation.m
  SmartDeviceLink/public/SDLChoiceCell.h
  SmartDeviceLink/public/SDLChoiceCell.m
  SmartDeviceLink/public/SDLChoiceSet.h
  SmartDeviceLink/public/SDLChoiceSet.m
  SmartDeviceLink/public/SDLFile.m
  SmartDeviceLink/public/SDLMenuCell.h
  SmartDeviceLink/public/SDLMenuCell.m
  SmartDeviceLink/public/SDLScreenManager.h
  SmartDeviceLinkTests/DevAPISpecs/NSArray+ExtensionsSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLChoiceCellSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLChoiceSetManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLChoiceSetSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLFileManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLMenuCellSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLMenuManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLPreloadChoicesOperationSpec.m
Labels: manager-screen, proposal

#1935 Fix size of bulk data in PutFile
  SmartDeviceLink/private/SDLUploadFileOperation.m
  SmartDeviceLinkTests/DevAPISpecs/SDLUploadFileOperationSpec.m
Labels: bug

#1756 [SDL-0296] Feature/ possibility to update video streaming capabilities
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
  SmartDeviceLink/private/SDLCarWindow.h
  SmartDeviceLink/private/SDLCarWindow.m
  SmartDeviceLink/private/SDLImageResolution + StreamingVideoExtensions.h
  SmartDeviceLink/private/SDLImageResolution + StreamingVideoExtensions.m
  SmartDeviceLink/private/SDLRPCParameterNames.h
  SmartDeviceLink/private/SDLRPCParameterNames.m
  SmartDeviceLink/private/SDLStreamingVideoLifecycleManager.h
  SmartDeviceLink/private/SDLStreamingVideoLifecycleManager.m
  SmartDeviceLink/private/SDLVideoStreamingCapability + StreamingVideoExtensions.h
  SmartDeviceLink/private/SDLVideoStreamingCapability + StreamingVideoExtensions.m
  SmartDeviceLink/public/SDLAppCapability.h
  SmartDeviceLink/public/SDLAppCapability.m
  SmartDeviceLink/public/SDLAppCapabilityType.h
  SmartDeviceLink/public/SDLAppCapabilityType.m
  SmartDeviceLink/public/SDLFunctionID.m
  SmartDeviceLink/public/SDLHapticRect.m
  SmartDeviceLink/public/SDLImageResolution.h
  SmartDeviceLink/public/SDLImageResolution.m
  SmartDeviceLink/public/SDLOnAppCapabilityUpdated.h
  SmartDeviceLink/public/SDLOnAppCapabilityUpdated.m
  SmartDeviceLink/public/SDLRPCFunctionNames.h
  SmartDeviceLink/public/SDLRPCFunctionNames.m
  SmartDeviceLink/public/SDLRectangle.m
  SmartDeviceLink/public/SDLStreamingMediaConfiguration.h
  SmartDeviceLink/public/SDLStreamingVideoDelegate.h
  SmartDeviceLink/public/SDLStreamingVideoScaleManager.h
  SmartDeviceLink/public/SDLStreamingVideoScaleManager.m
  SmartDeviceLink/public/SDLSystemCapability.m
  SmartDeviceLink/public/SDLSystemCapabilityManager.m
  SmartDeviceLink/public/SDLTouchManager.m
  SmartDeviceLink/public/SDLVideoStreamingCapability.h
  SmartDeviceLink/public/SDLVideoStreamingCapability.m
  SmartDeviceLink/public/SDLVideoStreamingFormat.m
  SmartDeviceLink/public/SDLVideoStreamingRange.h
  SmartDeviceLink/public/SDLVideoStreamingRange.m
  SmartDeviceLink/public/SmartDeviceLink.h
  SmartDeviceLinkTests/DevAPISpecs/SDLLifecycleManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m
  SmartDeviceLinkTests/ProtocolSpecs/MessageSpecs/SDLProtocolSpec.m
  SmartDeviceLinkTests/ProtocolSpecs/SDLFunctionIDSpec.m
  SmartDeviceLinkTests/ProxySpecs/SDLHapticManagerSpec.m
  SmartDeviceLinkTests/RPCSpecs/EnumSpecs/SDLAppCapabilityTypeSpec.m
  SmartDeviceLinkTests/RPCSpecs/NotificationSpecs/SDLOnAppCapabilityUpdatedSpec.m
  SmartDeviceLinkTests/RPCSpecs/RequestSpecs/SDLRegisterAppInterfaceSpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLAppCapabilitySpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLImageResolutionSpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLRectangleSpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLVideoStreamingCapabilitySpec.m
  SmartDeviceLinkTests/SDLCarWindowSpec.m
  SmartDeviceLinkTests/SDLStreamingMediaManagerSpec.m
  SmartDeviceLinkTests/SDLStreamingVideoScaleManagerSpec.m
  SmartDeviceLinkTests/SDLSupportedStreamingRangeSpec.m
  SmartDeviceLinkTests/SDLSystemCapabilityManagerSpec.m
  SmartDeviceLinkTests/TestSmartConnection.h
  SmartDeviceLinkTests/TestSmartConnection.m
  SmartDeviceLinkTests/TestSmartConnectionManager.h
  SmartDeviceLinkTests/TestSmartConnectionManager.m
  SmartDeviceLinkTests/TestStreamingMediaDelegate.h
  SmartDeviceLinkTests/TestStreamingMediaDelegate.m
Labels: manager-streaming-video, proposal

#1937 Fix main menu UI updates do not take text field name image field name into consideration
  SmartDeviceLink/private/SDLMenuManager.m
Labels: bug, manager-screen

#1930 Increase the timeout on some tests to fix CI fails
  SmartDeviceLinkTests/DevAPISpecs/SDLAsynchronousRPCRequestOperationSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLAudioStreamManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLFileManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLLifecycleManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLSequentialRPCRequestOperationSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLSoftButtonManagerSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m
  SmartDeviceLinkTests/ProxySpecs/SDLSecondaryTransportManagerSpec.m
  SmartDeviceLinkTests/SDLAlertManagerSpec.m
  SmartDeviceLinkTests/SDLAsynchronousRPCOperationSpec.m
  SmartDeviceLinkTests/SDLPresentAlertOperationSpec.m
  SmartDeviceLinkTests/SDLSystemCapabilityManagerSpec.m
Labels: testing

#1939 Fixes related to auxillary
  SmartDeviceLink/public/SDLStaticIconName.h
  SmartDeviceLink/public/SDLStaticIconName.m
  SmartDeviceLinkTests/RPCSpecs/EnumSpecs/SDLStaticIconNameSpec.m
Labels: bug

#1912 Fix choice set default timeout behavior
  SmartDeviceLink/public/SDLChoiceSet.h
  SmartDeviceLink/public/SDLChoiceSet.m
  SmartDeviceLinkTests/DevAPISpecs/SDLChoiceSetSpec.m
Labels: bug, manager-screen

#1910 Refactor IAP Transport / Fix EASessions left open
  SmartDeviceLink/private/SDLIAPControlSession.h
  SmartDeviceLink/private/SDLIAPControlSession.m
  SmartDeviceLink/private/SDLIAPControlSessionDelegate.h
  SmartDeviceLink/private/SDLIAPDataSession.h
  SmartDeviceLink/private/SDLIAPDataSession.m
  SmartDeviceLink/private/SDLIAPDataSessionDelegate.h
  SmartDeviceLink/private/SDLIAPSession.h
  SmartDeviceLink/private/SDLIAPSession.m
  SmartDeviceLink/private/SDLIAPTransport.m
  SmartDeviceLinkTests/TransportSpecs/iAP/SDLIAPControlSessionSpec.m
  SmartDeviceLinkTests/TransportSpecs/iAP/SDLIAPDataSessionSpec.m
  SmartDeviceLinkTests/TransportSpecs/iAP/SDLIAPSessionSpec.m
  SmartDeviceLinkTests/TransportSpecs/iAP/SDLIAPTransportSpec.m
Labels: bug, transport-iap

#1911 Prevent incorrect background processing
  SmartDeviceLink/private/SDLLifecycleManager.m
Labels: bug, manager-lifecycle

#1946 Fixes for APIs and naming
  Example Apps/Example ObjC/MenuManager.m
  Example Apps/Example ObjC/VehicleDataManager.m
  Example Apps/Example Swift/MenuManager.swift
  Example Apps/Example Swift/ProxyManager.swift
  Example Apps/Example Swift/VehicleDataManager.swift
  Example Apps/Shared/AppConstants.h
  Example Apps/Shared/AppConstants.m
  SmartDeviceLink-iOS.xcodeproj/project.pbxproj
  SmartDeviceLink/private/SDLImageResolution+StreamingVideoExtensions.h
  SmartDeviceLink/private/SDLImageResolution+StreamingVideoExtensions.m
  SmartDeviceLink/private/SDLStreamingVideoLifecycleManager.m
  SmartDeviceLink/private/SDLVideoStreamingCapability+StreamingVideoExtensions.h
  SmartDeviceLink/private/SDLVideoStreamingCapability+StreamingVideoExtensions.m
  SmartDeviceLink/public/SDLManagerDelegate.h
  SmartDeviceLink/public/SDLMenuCell.h
  SmartDeviceLink/public/SDLSeekStreamingIndicator.h
  SmartDeviceLink/public/SDLSeekStreamingIndicator.m
  SmartDeviceLink/public/SDLStreamingMediaConfiguration.h
  SmartDeviceLink/public/SDLStreamingMediaConfiguration.m
  SmartDeviceLink/public/SDLStreamingVideoDelegate.h
  SmartDeviceLink/public/SDLVideoStreamingCapability.m
  SmartDeviceLink/public/SDLVideoStreamingRange.m
  SmartDeviceLinkTests/DevAPISpecs/SDLChoiceSetSpec.m
  SmartDeviceLinkTests/DevAPISpecs/SDLStreamingMediaConfigurationSpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLSeekStreamingIndicatorSpec.m
  SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLVideoStreamingCapabilitySpec.m
Labels: best practice

#1947 Fixed video not resuming when switching between navigation apps
  SmartDeviceLink/private/SDLStreamingVideoLifecycleManager.m
Labels: bug, manager-streaming-video
